export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[] };

const p = (text: string): ArticleBlock => ({ type: "p", text });
const h2 = (text: string): ArticleBlock => ({ type: "h2", text });
const h3 = (text: string): ArticleBlock => ({ type: "h3", text });
const list = (items: string[]): ArticleBlock => ({ type: "list", items });

export type Article = {
  slug: string;
  title: string;
  category:
    | "Strategy"
    | "Transformation"
    | "Productivity"
    | "Leadership"
    | "Career"
    | "Business Analysis";
  description: string;
  date: string;
  readingTime: string;
  featured?: boolean;
  body: ArticleBlock[];
};

// Real posts, repurposed from Tola's LinkedIn writing. Dates are estimated
// (spaced out, most recent first) — swap in the actual publish dates
// whenever they're available.
export const articles: Article[] = [
  {
    slug: "three-lessons-leading-strategy-in-a-complex-industry",
    title: "3 Lessons I Learned Leading Strategy in a Complex Industry",
    category: "Strategy",
    description:
      "The neat version of strategy rarely survives contact with a real organization. Three lessons that have shaped how I think about strategy work.",
    date: "2026-08-05",
    readingTime: "2 min read",
    featured: true,
    body: [
      p("Working in strategy has taught me that the neat version of strategy we learn from frameworks rarely survives contact with a real organization."),
      p("The slides may look structured."),
      p("The business usually is not."),
      p("There are competing priorities, resource constraints, legacy decisions, stakeholder interests, regulatory realities, market uncertainty, and the simple challenge of getting different teams to move in the same direction."),
      p("Over time, three lessons have shaped how I think about strategy work."),
      h2("1. A good strategy needs organizational reality"),
      p("It is easy to design an ambitious strategy."),
      p("The harder question is whether the organization can execute it."),
      p("A company may want to launch several new products, enter new markets, transform operations, and reduce costs at the same time."),
      p("Each initiative may make sense independently."),
      p("Together, they may exceed the organization's capacity."),
      p("Strategy therefore has to account for people, systems, funding, leadership bandwidth, capabilities, and existing commitments."),
      p("Sometimes the smartest strategic decision is sequencing."),
      p("Do this first."),
      p("Build this capability next."),
      p("Enter that market later."),
      p("Ambition matters, but execution capacity matters too."),
      h2("2. Stakeholder management is part of strategy"),
      p("I used to think stakeholder management sat around the strategy."),
      p("Experience has taught me that it sits inside it."),
      p("Strategic decisions affect different groups differently."),
      p("A restructuring may improve efficiency while changing someone's span of control."),
      p("A new technology may improve productivity while creating uncertainty for employees."),
      p("A pricing decision may strengthen margins while creating pressure for commercial teams."),
      p("Ignoring these dynamics does not make them disappear."),
      p("Strong strategy leaders understand who will be affected, where resistance may come from, what concerns are legitimate, and where alignment needs to happen early."),
      p("A technically sound strategy can still fail when the people responsible for executing it do not support it."),
      h2("3. Execution discipline matters more than excitement"),
      p("Strategy launches often have energy."),
      p("People are enthusiastic. Leadership is aligned. Presentations look impressive."),
      p("Six months later, reality looks different."),
      p("Urgent operational issues have taken over. Some initiatives are behind schedule. Others have lost executive attention."),
      p("This is why strategy requires governance."),
      list([
        "Clear owners.",
        "Measurable outcomes.",
        "Regular reviews.",
        "Visible accountability.",
        "Fast escalation of blockers.",
      ]),
      p("And sometimes the discipline to stop initiatives that no longer make sense."),
      p("I have come to see strategy less as an annual event and more as a continuous management process."),
      p("You make choices, execute them, learn, adjust, and make new choices."),
      p("The frameworks help."),
      p("The harder work is building an organization capable of turning those frameworks into results."),
    ],
  },
  {
    slug: "three-signs-your-organization-is-ready-for-true-transformation",
    title: "3 Signs Your Organization Is Ready for True Transformation",
    category: "Transformation",
    description:
      "Transformation goes deeper than a new system or structure. Three signs that an organization is actually ready for that level of change.",
    date: "2026-07-29",
    readingTime: "2 min read",
    body: [
      p("Transformation is one of those words that gets used for almost everything."),
      p("A new technology platform becomes a digital transformation."),
      p("A restructuring becomes an organizational transformation."),
      p("A process improvement program becomes an operational transformation."),
      p("Some of these initiatives create meaningful change."),
      p("Others end up producing new systems and new structures while the organization continues working almost exactly as it did before."),
      p("True transformation goes deeper."),
      p("It changes how an organization operates, competes, serves customers, allocates resources, and makes decisions."),
      p("And there are usually signs that an organization is ready for that level of change."),
      h2("1. Leadership agrees that the current model cannot continue"),
      p("Transformation becomes difficult when leadership sees change as optional."),
      p("There needs to be a shared understanding of the problem."),
      p("Maybe customer expectations have changed. Costs are becoming unsustainable. Growth has slowed. Technology is disrupting the industry. Competitors are moving faster. Internal complexity is making execution difficult."),
      p("Whatever the trigger, leadership has to recognize that incremental improvements will not be enough."),
      p("This alignment matters because transformation eventually involves uncomfortable decisions."),
      p("Budgets may shift. Roles may change. Existing processes may disappear. Some initiatives may lose funding."),
      p("If leaders do not agree on the need for change, these decisions quickly become political."),
      h2("2. The organization is willing to change how work gets done"),
      p("Transformation cannot live only in strategy presentations."),
      p("Eventually, it reaches operating processes."),
      p("Teams may need different capabilities. Decision rights may have to change. Technology may replace manual work. Performance measures may need to be redesigned."),
      p("This is often where resistance begins."),
      p("Organizations ready for transformation understand that change may affect familiar routines and established power structures."),
      p("People need clarity about why the change matters, what will be different, and how they will be supported."),
      h2("3. Leadership is prepared to sustain attention"),
      p("Transformation takes time."),
      p("The launch usually gets the most energy."),
      p("There are town halls, workshops, project teams, communications, dashboards, and steering committees."),
      p("Then normal business pressure returns."),
      p("The organizations that succeed maintain leadership attention long after the initial excitement has disappeared."),
      p("They track outcomes, resolve bottlenecks, remove competing priorities, and hold people accountable."),
      p("They also adjust when assumptions change."),
      p("Transformation readiness ultimately comes down to willingness."),
      p("Willingness to acknowledge that the current model needs to evolve. Willingness to change how the organization works. And willingness to keep pushing after the project has lost its novelty."),
      p("Organizations that have those three things already have a strong foundation for meaningful transformation."),
    ],
  },
  {
    slug: "why-strategy-isnt-about-planning-its-about-prioritizing",
    title: "Why Strategy Isn't About Planning. It's About Prioritizing",
    category: "Strategy",
    description:
      "Planning tells you what could be done. Strategy becomes useful when leadership decides where limited resources should go first.",
    date: "2026-07-22",
    readingTime: "2 min read",
    body: [
      p("One of the most common outputs of a strategy process is a long list of initiatives."),
      p("Improve customer experience."),
      p("Expand into new markets."),
      p("Digitize operations."),
      p("Launch new products."),
      p("Reduce costs."),
      p("Strengthen talent."),
      p("Build brand awareness."),
      p("Increase revenue."),
      p("All of these may be sensible."),
      p("The problem is that an organization cannot pursue everything with the same level of intensity."),
      p("Strategy becomes useful when leadership decides where limited resources should go first."),
      p("That is prioritization."),
      h2("Planning tells you what could be done"),
      p("Planning is important."),
      p("Organizations need goals, initiatives, timelines, budgets, owners, and milestones."),
      p("But planning alone can create the illusion of strategic clarity."),
      p("A detailed roadmap may still contain too many competing ambitions."),
      p("The real challenge is deciding what deserves disproportionate attention."),
      p("If five initiatives compete for the same technology team, which one wins?"),
      p("If the business has enough capital to enter only one new market, which market matters most?"),
      p("If management attention is limited, which problems should leadership personally spend time solving?"),
      p("Those decisions reveal the strategy."),
      h2("Every priority consumes something"),
      p("Priorities require resources."),
      list(["Money.", "People.", "Time.", "Leadership attention.", "Organizational energy."]),
      p("This is why prioritization cannot happen only in a PowerPoint presentation."),
      p("The choices have to appear in the operating model."),
      p("A strategic initiative with no budget will struggle."),
      p("A priority without an accountable executive will drift."),
      p("A transformation program competing with ten other major projects will move slowly."),
      p("Organizations often need to reduce the number of things they are trying to do before execution improves."),
      h2("Saying no protects the strategy"),
      p("One of the hardest parts of strategy is turning down good opportunities."),
      p("Some opportunities will make money."),
      p("Some projects will solve genuine problems."),
      p("Some requests will come from influential stakeholders."),
      p("The question is whether they support the choices the organization has made."),
      p("Every additional initiative creates another demand on finite capacity."),
      p("That is why leadership teams need a consistent way to evaluate opportunities."),
      list([
        "Does this support our strategic priorities?",
        "What outcome will it create?",
        "What resources will it require?",
        "What will we delay or stop if we approve it?",
      ]),
      p("That final question forces clarity."),
      p("Most organizations do not suffer from a shortage of ideas."),
      p("They struggle with too many competing ones."),
      p("Prioritization gives strategy its power."),
    ],
  },
  {
    slug: "three-strategy-pitfalls-that-can-derail-even-a-good-strategy",
    title: "3 Strategy Pitfalls That Can Derail Even a Good Strategy",
    category: "Strategy",
    description:
      "A strategy can make perfect sense on paper and still struggle. Three pitfalls organizations should pay closer attention to, and the fix for each.",
    date: "2026-07-15",
    readingTime: "4 min read",
    body: [
      p("Most organizations do not struggle because they have no strategy."),
      p("There is usually a strategy document somewhere. Priorities have been agreed. Targets have been set. Leadership has probably spent hours debating where the business should go next."),
      p("The harder part is getting the organization to move in that direction consistently."),
      p("Over the years, working across strategy, transformation, and execution roles, I have seen a few patterns show up repeatedly. A strategy can make perfect sense on paper and still struggle once it meets the realities of competing priorities, limited resources, unclear ownership, and day-to-day operations."),
      p("Here are three pitfalls I think organizations should pay closer attention to."),
      h2("1. Trying to Do Too Much at Once"),
      p("One of the easiest ways to weaken a strategy is to call everything a priority."),
      p("You see a strategic plan with eight priorities, 20 initiatives and dozens of projects sitting underneath them. Each one may be reasonable on its own, but collectively they create a problem."),
      p("The organization simply does not have enough management attention, people, money or time to execute all of them well."),
      p("Teams end up spreading themselves across too many initiatives. Leaders spend meetings moving from one project update to another. Progress happens everywhere, but often not enough in the areas that matter most."),
      p("A good strategy requires choices."),
      h3("The fix: Force prioritization"),
      p("Leadership should be able to answer a few questions clearly:"),
      list([
        "What are the three to five outcomes that matter most over this period?",
        "Which initiatives will have the greatest impact on those outcomes?",
        "What are we deliberately choosing not to do?",
        "Where should our best people, capital and leadership attention go?",
      ]),
      p("That final question matters."),
      p("If something is genuinely a strategic priority, the way the organization allocates its resources should reflect that priority."),
      p("Strategy becomes much easier to execute when people know what deserves disproportionate attention."),
      h2("2. Leaving Strategy at the Leadership Level"),
      p("Another common problem is assuming that once leadership understands the strategy, the organization understands it too."),
      p("Usually, that is not the case."),
      p("A CEO may say, \"We need to improve customer retention.\""),
      p("The Head of Sales hears one thing. Operations hears another. Product interprets it differently. Someone three levels down may not know what the priority means for their work at all."),
      p("The strategy becomes weaker each time it travels through the organization."),
      p("Eventually, people return to doing what they have always done because nobody has translated the strategic priority into specific actions, targets and decisions."),
      h3("The fix: Translate strategy into execution"),
      p("Every strategic priority should cascade into clear outcomes at the relevant levels of the organization."),
      p("If improving customer retention is a priority, what does that mean for:"),
      list(["Product?", "Customer service?", "Sales?", "Operations?", "Technology?"]),
      p("Each team should understand the contribution it is expected to make, how that contribution will be measured and how it connects to the broader objective."),
      p("This is also where communication matters."),
      p("Mentioning the strategy once at an annual town hall is rarely enough. Leaders have to repeat it, explain it in different contexts and use it when making everyday decisions."),
      p("People understand what matters to an organization by watching what its leaders consistently talk about, measure and reward."),
      h2("3. Treating Strategy as an Annual Exercise"),
      p("I have seen organizations put significant effort into developing annual strategy plans."),
      p("There are workshops. Presentations. Financial models. Targets. Detailed initiatives."),
      p("Then everyone goes back to work."),
      p("Three months later, some initiatives have stalled. Others are behind schedule. A few no longer make sense because market conditions have changed. Yet the strategy is barely discussed until the next planning cycle."),
      p("That creates a gap between strategy development and strategy management."),
      p("A strategy should not become static simply because the planning process is complete."),
      h3("The fix: Build a strategy execution rhythm"),
      p("Execution needs a cadence."),
      p("For each strategic priority, there should be clear ownership, measurable outcomes and regular reviews."),
      p("A monthly or quarterly strategy review should answer questions such as:"),
      list([
        "Are we making the progress we expected?",
        "Which initiatives are behind?",
        "What is preventing execution?",
        "Have any assumptions changed?",
        "Do we need to reallocate resources?",
        "Does an initiative need to be stopped entirely?",
      ]),
      p("These conversations should focus on decisions rather than lengthy status updates."),
      p("Sometimes the right response to poor performance is to push harder. Sometimes the underlying assumption behind an initiative has changed and the strategy itself needs to evolve."),
      p("Strong execution requires knowing the difference."),
      h2("Strategy Is a Management Discipline"),
      p("Writing a strategy is only one part of the work."),
      p("The real test comes afterwards."),
      p("Can the organization make difficult choices about what matters most? Can it translate those choices into clear responsibilities across teams? Can leadership maintain enough discipline to review progress, resolve bottlenecks and adjust when circumstances change?"),
      p("Organizations that do these things consistently give their strategies a much better chance of succeeding."),
      p("Because ultimately, a strategy creates value through the hundreds of decisions, resource allocations and actions that happen after the strategy deck has been closed."),
    ],
  },
  {
    slug: "the-three-horizons-of-innovation",
    title: "The 3 Horizons of Innovation: Balancing Now, Next & New",
    category: "Transformation",
    description:
      "Where should leaders invest for growth? The Three Horizons framework offers a useful way to balance today's business against tomorrow's.",
    date: "2026-07-08",
    readingTime: "2 min read",
    body: [
      p("One of the hardest questions leaders face is where to invest for growth."),
      p("The business needs to perform today."),
      p("It also needs to prepare for tomorrow."),
      p("And somewhere inside the organization, people need to be thinking about opportunities that may not generate meaningful revenue for several years."),
      p("Those priorities compete for the same resources."),
      p("The Three Horizons framework provides a useful way to think about the balance."),
      h2("Horizon 1: Protect and improve the core"),
      p("Horizon 1 is today's business."),
      p("These are the products, services, customers, and markets currently generating most of the organization's revenue."),
      p("Innovation here usually focuses on improvement."),
      p("How can we serve customers better?"),
      p("How can we lower costs?"),
      p("How can we improve the product?"),
      p("How can we increase conversion, retention, or productivity?"),
      p("This work may sound less exciting than launching something completely new, but it matters."),
      p("The core business usually funds everything else."),
      p("Ignoring it in the pursuit of future growth can weaken the entire organization."),
      h2("Horizon 2: Build emerging growth engines"),
      p("Horizon 2 includes opportunities that are showing potential but have not yet become major contributors."),
      p("That could mean entering a new customer segment, launching an adjacent product, expanding geographically, or developing a new distribution channel."),
      p("These opportunities need investment and patience."),
      p("They also need different expectations."),
      p("A new business cannot always be evaluated using the same metrics as a mature business."),
      p("Early-stage growth may require leaders to pay more attention to adoption, learning, customer feedback, and product-market fit."),
      h2("Horizon 3: Explore the future"),
      p("Horizon 3 contains longer-term bets."),
      list(["New technologies.", "New business models.", "Unfamiliar markets.", "Ideas whose commercial potential may still be uncertain."]),
      p("Most Horizon 3 ideas will never become large businesses."),
      p("That is normal."),
      p("The purpose is to create options for the future."),
      p("The challenge is balance."),
      p("Organizations under pressure often concentrate entirely on Horizon 1 because today's numbers feel urgent."),
      p("Other organizations become fascinated by future innovation while neglecting the business that funds it."),
      p("Strong innovation portfolios create room for all three."),
      p("Improve what works today."),
      p("Build the opportunities that could drive tomorrow."),
      p("Keep exploring what may matter after that."),
      p("Innovation becomes more sustainable when leaders stop treating every opportunity as if it belongs to the same timeline."),
    ],
  },
  {
    slug: "innovation-dies-when-fear-leads",
    title: "Innovation Dies When Fear Leads: How Culture Kills Great Ideas",
    category: "Leadership",
    description:
      "Sometimes employees aren't the problem. The environment is. How fear quietly teaches people to stop sharing ideas, and what changes it.",
    date: "2026-07-01",
    readingTime: "2 min read",
    body: [
      p("I have always found it interesting when organizations say employees are not innovative enough."),
      p("Sometimes the employees are not the problem."),
      p("The environment is."),
      p("People learn quickly what is safe inside an organization."),
      p("They notice what happens when someone challenges a senior colleague. They see how managers respond when an experiment fails. They watch whether unusual ideas are explored or dismissed."),
      p("Over time, employees build an internal map of acceptable behavior."),
      p("If speaking up creates risk, people become quieter."),
      p("If failure attracts blame, people become cautious."),
      p("If every new idea requires several layers of approval, people stop trying."),
      p("And gradually, an organization that says it wants innovation creates a culture designed to prevent it."),
      h2("Fear makes people optimize for safety"),
      p("Innovation involves proposing something that may not work."),
      p("That requires psychological and professional safety."),
      p("Employees need to believe they can ask questions, challenge assumptions, and suggest alternatives without damaging their reputation."),
      p("This does not mean every idea should be approved."),
      p("Some ideas will be impractical. Others will be poorly thought through."),
      p("The important thing is how the organization responds."),
      p("A respectful \"no\" keeps people thinking."),
      p("Ridicule, punishment, or automatic dismissal teaches people to stay silent."),
      h2("Leaders shape the innovation culture"),
      p("Employees rarely take cultural cues from posters on the wall."),
      p("They watch leaders."),
      p("When someone brings a different perspective into a meeting, does the manager become defensive or curious?"),
      p("When a pilot underperforms, does leadership ask what was learned or look for someone to blame?"),
      p("When junior employees identify problems, are they taken seriously?"),
      p("These moments matter more than innovation workshops."),
      h2("Make small bets easier"),
      p("One reason innovation becomes intimidating is that organizations treat every new idea like a major investment decision."),
      p("Many ideas do not need that level of commitment."),
      p("A team can test a new process for two weeks."),
      p("A product concept can be piloted with a small customer segment."),
      p("A new service approach can be tested in one location."),
      p("Small experiments reduce the cost of failure while increasing the speed of learning."),
      p("Culture determines whether those experiments happen."),
      p("When employees know they can challenge assumptions, test ideas responsibly, and learn from what does not work, innovation becomes part of everyday behavior."),
      p("Fear has the opposite effect."),
      p("People rarely stop having ideas."),
      p("They simply stop sharing them."),
    ],
  },
  {
    slug: "why-some-strategies-fail-the-people-problem",
    title: "Why Some Strategies Fail: The People Problem",
    category: "Strategy",
    description:
      "A strategy can be logically sound and still fail. Usually because people, not the plan, were never accounted for.",
    date: "2026-06-24",
    readingTime: "2 min read",
    body: [
      p("A strategy can be logically sound and still fail."),
      p("The market analysis may be correct."),
      p("The financial case may be convincing."),
      p("The initiatives may make sense."),
      p("The targets may even be achievable."),
      p("And yet, months later, progress is slow."),
      p("One reason is that organizations sometimes design strategy as though people will automatically behave differently once a new direction has been announced."),
      p("They usually will not."),
      p("People carry existing incentives, habits, priorities, relationships, fears, and ways of working into the new strategy."),
      p("If those things remain unchanged, execution becomes difficult."),
      h2("People need to understand what the strategy means for them"),
      p("Senior leaders may understand the strategic narrative perfectly."),
      p("Employees often receive a simplified version during a town hall or through an email."),
      p("That leaves an important gap."),
      list([
        "What should I do differently?",
        "Which priorities have changed?",
        "What should I stop doing?",
        "How will success be measured?",
      ]),
      p("When those questions are unanswered, people default to familiar behavior."),
      p("Strategy becomes another leadership initiative running alongside normal work."),
      h2("Incentives can quietly defeat strategy"),
      p("Imagine an organization says collaboration is critical, but individual performance metrics reward teams for protecting their own targets."),
      p("Or leadership says customer experience is the priority, but employees are measured primarily on speed."),
      p("People eventually respond to what gets measured and rewarded."),
      p("This is why strategy execution requires alignment between strategic priorities and the performance system."),
      p("The organization has to make the desired behavior rational."),
      h2("Managers translate strategy into reality"),
      p("Middle managers play an underrated role."),
      list([
        "They decide what teams discuss every week.",
        "They allocate work.",
        "They resolve trade-offs.",
        "They interpret leadership messages.",
        "They shape how seriously employees take new priorities.",
      ]),
      p("If managers are not aligned, equipped, and accountable, strategic messages can lose meaning as they travel through the organization."),
      p("This is why communication alone rarely solves execution problems."),
      p("People need context, clarity, capability, incentives, and reinforcement."),
      p("A strategy becomes real when thousands of individual decisions begin moving in the same direction."),
      p("The strategy document matters."),
      p("The people who have to bring it to life matter even more."),
    ],
  },
  {
    slug: "eight-career-lessons-im-still-learning",
    title: "Eight Career Lessons I'm Still Learning",
    category: "Career",
    description:
      "Eight lessons on growth, reputation, and feedback, gathered one birthday at a time.",
    date: "2026-06-17",
    readingTime: "2 min read",
    body: [
      p("My birthday was last week, and it had me thinking about how much I've grown, not just as a person, but as a professional."),
      p("In that spirit, here are eight career lessons that have shaped me and continue to shape me."),
      p("1. You won't grow if you don't do the hard work."),
      p("Stretch roles are uncomfortable for a reason. They expose your blind spots and stretch your capacity. Growth doesn't come from staying safe. It comes from choosing the path that demands more of you."),
      p("2. Relationships open more doors than resumes."),
      p("Your network isn't just about who you know. It's about who believes in you. The people you build real trust with will mention your name in rooms you've never entered."),
      p("3. Your reputation is built when no one's watching."),
      p("It's easy to show up well on presentation day. What actually shapes your brand is how you respond to pressure, handle small tasks, and treat colleagues when it doesn't count for anything. Consistency beats performance."),
      p("4. Clarity comes from movement, not waiting."),
      p("You won't figure it all out by sitting on the fence. Every meaningful career move I've made started with a step I wasn't fully sure about. Direction gets clearer the further you walk."),
      p("5. Feedback isn't personal, so don't take it personally."),
      p("Early on, I used to feel embarrassed when someone pointed out what I could have done better. Now I treat it as a growth hack. Feedback isn't about your worth. It's about your potential."),
      p("6. Put your hand up for the big projects."),
      p("Even when you feel underqualified. Especially when you feel underqualified. You'll never have all the answers upfront, but taking on real responsibility is what forces you to rise."),
      p("7. A growth mindset changes everything."),
      p("You will make mistakes and fumble things. Every time you choose to learn instead of sulk, you gain something. Let go of the pressure to be perfect and lean into asking what you can learn."),
      p("8. People work harder for leaders who care about them."),
      p("Deadlines and KPIs matter. But the people doing the work matter more. I've seen firsthand how much more motivated and loyal people become when they feel seen, heard, and genuinely cared for."),
    ],
  },
  {
    slug: "the-real-cost-of-ignoring-innovation",
    title: "The Real Cost of Ignoring Innovation: Lessons from Kodak and Nokia",
    category: "Transformation",
    description:
      "Kodak and Nokia weren't unaware of what was happening. Their challenge was deeper, and it's a lesson every market leader should sit with.",
    date: "2026-06-10",
    readingTime: "2 min read",
    body: [
      p("Kodak and Nokia are often used as cautionary stories in conversations about innovation."),
      p("Both companies were dominant in their industries."),
      p("Kodak became almost synonymous with photography. Nokia once controlled a huge share of the global mobile phone market."),
      p("And both eventually lost their positions as their industries changed around them."),
      p("The interesting part is that neither company was completely unaware of what was happening."),
      p("Kodak famously developed one of the earliest digital cameras in the 1970s. Nokia had strong engineering capabilities, global distribution, a powerful brand, and significant resources."),
      p("Their challenge was deeper."),
      p("Successful business models can make change uncomfortable."),
      p("When an organization has spent years building capabilities, revenue streams, processes, and incentives around a particular model, new ideas can feel threatening."),
      p("A new technology may create opportunity for the company while simultaneously weakening the business that currently pays the bills."),
      p("That creates a difficult strategic tension."),
      h2("Success can make organizations defensive"),
      p("When a business model is working, protecting it feels rational."),
      p("Leaders are responsible for revenue, profitability, market share, and shareholder expectations. Investments in unfamiliar technologies may look risky compared with continuing to invest in proven products."),
      p("The problem comes when protecting today's business prevents the organization from building tomorrow's."),
      p("Kodak's film business was highly profitable. Digital photography challenged the economics of that business."),
      p("Nokia's dominance in mobile hardware became less valuable as smartphones increasingly competed through software ecosystems, applications, and user experience."),
      p("The market changed faster than their organizations could respond."),
      h2("Innovation requires cannibalization sometimes"),
      p("One of the hardest strategic decisions is choosing to disrupt your own successful product."),
      p("Leaders naturally hesitate."),
      p("Why launch something that could reduce revenue from your existing offer?"),
      p("Because if customer behavior is changing, someone else may do it anyway."),
      p("Organizations that innovate well are willing to place selective bets on businesses that may eventually compete with their current model."),
      h2("Pay attention to weak signals"),
      p("Major disruption rarely arrives completely unannounced."),
      p("Customer preferences shift gradually. New competitors appear at the edges of the market. Technologies improve. Business models that once looked niche begin to scale."),
      p("The organizations that respond early have more options."),
      p("The cost of ignoring innovation goes far beyond losing market share."),
      p("You lose time."),
      p("And once an industry has moved significantly, catching up becomes much more expensive."),
      p("The lesson from Kodak and Nokia is simple."),
      p("Market leadership is temporary."),
      p("Organizations have to keep earning their relevance."),
    ],
  },
  {
    slug: "strategy-is-not-a-plan-its-a-set-of-choices",
    title: "Strategy Is Not a Plan. It's a Set of Choices",
    category: "Strategy",
    description:
      "The most useful strategy question isn't what will we do. It's what has the organization decided not to do.",
    date: "2026-06-03",
    readingTime: "2 min read",
    body: [
      p("Many strategy documents are impressive."),
      p("They contain market analysis, financial projections, strategic pillars, initiatives, timelines, and pages of detailed recommendations."),
      p("But there is one question I often find more useful than almost anything else:"),
      p("What has the organization decided not to do?"),
      p("That question reveals how much real strategy has taken place."),
      p("A plan can contain dozens of activities."),
      p("Strategy requires choices."),
      p("Every organization has limited capital, people, management attention, and time. Choosing one direction means accepting that some other opportunities will receive less attention."),
      p("That is where strategy becomes difficult."),
      h2("Choices create focus"),
      p("Imagine a company deciding it wants to grow."),
      p("That sounds strategic, but it leaves many questions unanswered."),
      list([
        "Grow where?",
        "New customers or existing customers?",
        "New markets or existing markets?",
        "Premium products or mass market?",
        "Organic growth or acquisitions?",
        "Which customer segments matter most?",
        "What capabilities will the organization need?",
      ]),
      p("Until those choices are made, \"growth\" remains an ambition."),
      p("Good strategy gives the organization enough clarity to allocate resources confidently."),
      h2("Priorities need consequences"),
      p("Organizations frequently describe five, eight, or even ten things as strategic priorities."),
      p("The problem is that something cannot be a priority if it has no effect on how the organization behaves."),
      p("If customer experience is a priority, there should be investment behind it."),
      p("If digital transformation is a priority, technology capacity should reflect that."),
      p("If a new market is strategically important, leadership attention should move toward it."),
      p("Strategy shows up in budgets, hiring decisions, project portfolios, leadership agendas, and performance metrics."),
      p("That is where you see the choices."),
      h2("Trade-offs are uncomfortable"),
      p("One reason organizations avoid clear choices is that trade-offs create tension."),
      p("Every initiative has an advocate."),
      p("Every business unit believes its priorities are important."),
      p("Every opportunity can usually be supported by a reasonable argument."),
      p("Leadership has to decide which opportunities deserve disproportionate investment."),
      p("That may mean delaying a project, exiting a market, reducing investment in an existing product, or saying no to something that could still be profitable."),
      p("Those decisions are rarely easy."),
      p("But avoiding them does not eliminate the trade-off. It simply spreads resources more thinly."),
      p("A strong strategy gives people clarity about where the organization is going and what matters most along the way."),
      p("The quality of the strategy is often visible in the choices leadership is willing to make."),
    ],
  },
  {
    slug: "building-a-culture-of-everyday-innovation",
    title: "Building a Culture of Everyday Innovation",
    category: "Leadership",
    description:
      "Some of the most useful innovation inside organizations is much less dramatic than a product launch. It starts with making improvement part of normal work.",
    date: "2026-05-27",
    readingTime: "2 min read",
    body: [
      p("When people hear the word innovation, they often think about major product launches, disruptive technology, or billion-dollar ideas."),
      p("But some of the most useful innovation inside organizations is much less dramatic."),
      p("It happens when someone finds a better way to serve a customer. When a team removes an unnecessary step from a process. When an employee spots a recurring problem and proposes a simple fix. When people are encouraged to question how work gets done instead of accepting that \"this is how we have always done it.\""),
      p("That is everyday innovation."),
      p("The challenge is that many organizations say they want innovation while creating environments that make it difficult."),
      p("Employees are encouraged to bring ideas, but challenging an existing process can be interpreted as criticism. Teams are told to experiment, but mistakes are punished. Innovation appears in corporate values, but employees are measured almost entirely on delivering today's work."),
      p("Eventually, people learn what the organization truly values."),
      p("And they behave accordingly."),
      p("Building an innovative culture starts with making improvement part of normal work."),
      h2("Give people permission to question things"),
      p("Some of the best ideas come from people closest to the problem."),
      p("The customer service representative who handles the same complaint every week probably understands something about the customer experience that senior leadership does not."),
      p("The operations team may know exactly which process creates unnecessary delays."),
      p("The sales team probably hears objections that never appear in strategy presentations."),
      p("Organizations need mechanisms that allow these insights to travel upward."),
      p("That could mean regular improvement sessions, idea channels, retrospectives, innovation challenges, or simply managers consistently asking: \"What is making your work harder than it needs to be?\""),
      h2("Make experimentation safe"),
      p("Innovation involves uncertainty."),
      p("Some ideas will work. Others will not."),
      p("If every unsuccessful experiment becomes a career risk, people will quickly stop experimenting."),
      p("That does not mean accepting careless decisions. Good experimentation should still have clear hypotheses, boundaries, budgets, and measures of success."),
      p("The goal is to create room for intelligent testing."),
      h2("Reward improvement, not just outcomes"),
      p("People pay attention to what gets recognized."),
      p("If recognition only goes to teams that hit revenue targets or deliver major projects, smaller improvements can easily disappear."),
      p("Recognizing employees who simplify processes, reduce waste, improve customer experience, or identify new opportunities sends an important signal."),
      p("Innovation belongs to everyone."),
      p("A culture of everyday innovation is built through hundreds of small decisions."),
      p("It grows when employees feel comfortable speaking up, managers are willing to listen, and leaders create space for ideas to become experiments."),
      p("Organizations that get this right rarely have to tell employees to \"be innovative.\""),
      p("People already know that improving the way things work is part of the job."),
    ],
  },
  {
    slug: "the-biggest-mistake-i-made-early-in-my-career",
    title: "The Biggest Mistake I Made Early in My Career",
    category: "Career",
    description:
      "Doing good work was never the whole job. Visibility and relationships matter just as much as performance.",
    date: "2026-05-20",
    readingTime: "1 min read",
    body: [
      p("I once believed that doing good work was enough."),
      p("So I kept my head down, focused on delivering, avoided office politics, and assumed someone would eventually notice."),
      p("They didn't. And it wasn't because they were blind to my talent. It was because visibility, relationships, and communication matter just as much as performance, especially in complex organizations."),
      p("Here's what I've learned since:"),
      p("Your work should speak for you, but it shouldn't have to speak alone."),
      p("Build real relationships, not just transactional networks."),
      p("Learn to talk about your wins without it feeling like bragging. It's a skill worth practicing."),
      p("Don't assume your manager or leadership already knows everything you're doing."),
      p("I still believe in excellence. I just also believe in advocating for that excellence, connecting with the people around you, and building influence alongside output."),
    ],
  },
  {
    slug: "three-small-habits-that-changed-how-i-work",
    title: "Three Small Habits That Changed How I Work",
    category: "Productivity",
    description:
      "Three small daily shifts that made a bigger difference than any elaborate productivity system.",
    date: "2026-05-13",
    readingTime: "1 min read",
    body: [
      p("Productivity used to feel overwhelming, like it required a two-hour morning routine, five apps, and a life coach just to stay on top of things."),
      p("In reality, it was a few small shifts that made the biggest difference. Here are three habits that quietly changed how I work."),
      p("Start each day by writing your top three priorities."),
      p("No fancy planner required, just a sticky note or a notebook. It keeps me focused on what actually matters instead of what's simply urgent."),
      p("Use fifteen-minute time blocks."),
      p("Instead of waiting for a perfect two-hour window to do deep work, I started tackling tasks in short bursts. It beats procrastination almost every time."),
      p("Close the laptop at the same time every evening."),
      p("This one surprised me the most. That boundary helps me rest better, think more clearly, and show up stronger the next day."),
      p("None of these habits feel dramatic on their own. But stay consistent for a few months, and you'll notice something has genuinely shifted."),
    ],
  },
  {
    slug: "would-you-hire-you",
    title: "Would You Hire You?",
    category: "Leadership",
    description:
      "Five hard reminders from Matt Adolphe's Would You Hire You? on what actually makes someone worth hiring.",
    date: "2026-05-06",
    readingTime: "1 min read",
    body: [
      p("I recently read Would You Hire You? by Matt Adolphe, and I didn't expect it to hit as hard as it did."),
      p("The book is short and simple, but the questions it raises are not. Here are five reminders I walked away with."),
      p("Show up with solutions, not just problems. Pointing out what's wrong is easy. Suggesting what's next is leadership."),
      p("Be the kind of person others want on their team. Competence matters, but so does attitude, ownership, and how you treat people when no one's watching."),
      p("Be self-aware enough to fix your blind spots. Feedback isn't criticism. It's a growth tool, and it's wasted if you don't use it."),
      p("Consistency builds trust faster than charisma. No one hires your best day. They hire your every day."),
      p("You're always being interviewed, even when you're not. Your daily actions are your personal brand, and people notice more than you'd think."),
      p("It's a simple book, but taken seriously, it changes how you show up at work, on teams, and even outside of work."),
      p("Would you hire you?"),
    ],
  },
  {
    slug: "three-more-habits-worth-stealing",
    title: "Three More Habits Worth Stealing",
    category: "Productivity",
    description:
      "Three more small habits worth adopting, from a three-line to-do list to a ten-minute rule for beating procrastination.",
    date: "2026-04-29",
    readingTime: "1 min read",
    body: [
      p("For a long time I thought productivity required a complex system. It turns out the tiny habits, the ones that feel too small to matter, made the biggest difference."),
      p("Here are three that changed the game for me."),
      p("Starting the day with a three-line to-do list."),
      p("I used to overload my task list and feel defeated by mid-afternoon. Now I pick three high-impact tasks each morning and win the day before lunch."),
      p("Using the ten-minute rule to beat procrastination."),
      p("When I don't feel like starting something, I tell myself to just do it for ten minutes. Nine times out of ten I keep going, because starting is always the hardest part."),
      p("Closing the day with a short review."),
      p("Every evening I ask myself what I learned that day and what I could do better tomorrow. It keeps me grounded and focused on progress instead of perfection."),
      p("Productivity was never about doing more. It's about doing what matters, with clarity and consistency."),
    ],
  },
  {
    slug: "what-to-do-when-you-get-passed-over-for-a-promotion",
    title: "What to Do When You Get Passed Over for a Promotion",
    category: "Career",
    description:
      "Getting passed over for a promotion stings. Here's how I turned that disappointment into a turning point.",
    date: "2026-04-22",
    readingTime: "2 min read",
    body: [
      p("It's one of the most uncomfortable moments in any career: the promotions get announced, and your name isn't on the list."),
      p("I've been there. Everyone assumed I'd get promoted with my peers. Honestly, I did too. But I didn't. When I asked why, the feedback was direct: my performance review hadn't met the bar for the next level."),
      p("It stung, not because I felt entitled, but because I genuinely thought I'd done enough. Turns out I hadn't, and that was hard to accept."),
      p("But here's the part I'm most proud of. I didn't let that moment define me. I used it to refine me."),
      p("So, what should you do when you get passed over? Here's what helped me turn disappointment into a turning point."),
      p("1. Don't get defensive. Get curious."),
      p("It's tempting to assume politics or bias, and sometimes those do play a role. But start by asking what feedback you missed or ignored, and take ownership of the parts you can actually improve."),
      p("2. Understand what the next level really expects."),
      p("Job descriptions rarely tell you what actually matters. Talk to your manager, a mentor, or someone recently promoted, and ask what success looks like in that role. Then align your output to that, not just your current tasks."),
      p("3. Start working like you're already there."),
      p("Promotions reward proof, not potential. Lead meetings, take initiative, show maturity, and let your actions speak louder than your ambition."),
      p("4. Use feedback as a growth strategy."),
      p("I didn't treat the feedback I received as rejection. I treated it as data, and worked on the gaps it pointed to, not just to get promoted, but to actually grow stronger."),
      p("5. Say yes to big opportunities, even the scary ones."),
      p("Not long after, I got the chance to work on a major client project. It was complex and well outside my comfort zone, but showing up fully for it changed how leadership saw me. Sometimes the project is the promotion."),
      p("Getting passed over doesn't feel good. But it isn't a dead end. It can be a mirror, a classroom, and a launchpad. The goal was never just to get promoted. It's to become someone who can't be overlooked next time."),
      p("Have you ever been passed over for a promotion? What did it teach you?"),
    ],
  },
  {
    slug: "ever-felt-invisible-at-work",
    title: "Ever Felt Invisible at Work?",
    category: "Career",
    description:
      "Doing good work isn't always enough to get seen. A few shifts that helped me show up differently.",
    date: "2026-04-15",
    readingTime: "1 min read",
    body: [
      p("Like you're doing your best, but no one seems to notice?"),
      p("I've been there. You're showing up, delivering, trying, and somehow the recognition, the opportunities, the growth all seem to skip past you."),
      p("Here's the hard truth no one tells you: doing good work isn't always enough to get seen. Sometimes you have to strategically show up, not just work hard behind the scenes."),
      p("If you're feeling stuck or invisible at work, here are a few shifts that helped me and the people I've worked with."),
      p("Speak up, even when it feels uncomfortable. Volunteer updates, share your wins, suggest solutions. Let people hear your voice and see your value."),
      p("Document your impact. Keep a record of results you've driven, problems you've solved, and positive feedback you've received. It isn't bragging. It's preparation, especially when performance reviews come around."),
      p("Ask for feedback, and act on it. Sometimes you're not stuck, you're just unaware of what's holding you back."),
      p("Get visible beyond your team. Support cross-functional projects, join committees, ask to present in meetings. Visibility builds credibility."),
      p("Don't wait to be chosen. Start choosing yourself. Advocate for yourself the way you'd advocate for someone you believe in, because you should."),
      p("The workplace can feel like a maze at times. But growth doesn't always come from waiting for the next promotion. It comes from showing up differently: intentionally, boldly, and with clarity."),
      p("Have you ever felt invisible at work? What helped you break through?"),
    ],
  },
  {
    slug: "hire-giants-even-early-in-your-career",
    title: "Hire Giants, Even Early in Your Career",
    category: "Career",
    description:
      "David Ogilvy's nesting-doll lesson on hiring people bigger than yourself, and why it applies long before you're the one hiring.",
    date: "2026-04-08",
    readingTime: "1 min read",
    body: [
      p("David Ogilvy, often called the father of modern advertising, had a knack for sharing big lessons in simple ways."),
      p("Whenever he appointed a new office head, he would give them a set of Russian nesting dolls. Inside the smallest one was a note: if each of us hires people smaller than we are, the company becomes a company of dwarfs. But if each of us hires people bigger than we are, the company becomes a company of giants."),
      p("That lesson was aimed at managers, but it applies long before you're in a position to hire anyone. Early in your career, \"hiring bigger\" means actively seeking out people who are smarter, more experienced, or more skilled than you, and finding ways to work with or learn from them."),
      p("Here's how to apply it when you're just starting out:"),
      p("Choose projects that stretch you. Volunteer for work that forces you to learn from high performers."),
      p("Seek out mentors and peers who challenge you, not just people who think the way you do."),
      p("Ask for feedback from those ahead of you. Their perspective can help you grow faster than you would on your own."),
      p("The people you surround yourself with will either limit you or lift you. The sooner you choose giants, the sooner you'll grow into one."),
      p("Who are the giants in your workplace right now, and what have they taught you?"),
    ],
  },
];

export function getArticleBySlug(slug: string) {
  return articles.find((article) => article.slug === slug);
}
