export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[] };

const p = (text: string): ArticleBlock => ({ type: "p", text });
const h2 = (text: string): ArticleBlock => ({ type: "h2", text });
const h3 = (text: string): ArticleBlock => ({ type: "h3", text });
const list = (items: string[]): ArticleBlock => ({ type: "list", items });

export type Article = {
  slug: string;
  title: string;
  category:
    | "Strategy"
    | "Transformation"
    | "Productivity"
    | "Leadership"
    | "Career"
    | "Business Analysis";
  description: string;
  date: string;
  readingTime: string;
  featured?: boolean;
  body: ArticleBlock[];
};

// Real posts, repurposed from Tola's LinkedIn writing. Dates are estimated
// (spaced out, most recent first) — swap in the actual publish dates
// whenever they're available.
export const articles: Article[] = [
  {
    slug: "why-good-strategies-fail-in-execution",
    title: "Why Good Strategies Fail in Execution",
    category: "Strategy",
    description:
      "The problem is often less about the quality of the strategy and more about what happens after it's agreed. Three gaps that get in the way.",
    date: "2026-08-08",
    readingTime: "5 min read",
    body: [
      p("Organizations rarely suffer from a shortage of strategy."),
      p("Most companies have annual planning sessions, strategic priorities, growth targets, transformation programs, and detailed presentations explaining where the business wants to go. In many cases, a considerable amount of thought has gone into developing those plans."),
      p("Yet a year later, the results can look surprisingly different from what was intended."),
      p("Some initiatives have stalled. Others have quietly disappeared. Teams are still working in largely the same way, and leadership is wondering why a strategy that appeared sound on paper has produced so little change."),
      p("I have found that the problem is often less about the quality of the strategy itself and more about what happens after the strategy has been agreed."),
      p("A strategy only becomes useful when the rest of the organization can understand it, make decisions from it, and translate it into action."),
      p("Three gaps tend to get in the way."),
      h2("1. The Strategy Never Becomes Specific Enough"),
      p("Strategic plans naturally operate at a high level."),
      p("A company may decide to improve customer experience, accelerate digital transformation, expand into new markets, or become more innovative."),
      p("Those are valid strategic directions, but they are not yet actionable."),
      p("If the organization says customer experience is a priority, teams still need to understand:"),
      list([
        "Which parts of the customer journey need to improve?",
        "What outcomes are expected?",
        "Which teams are responsible for those outcomes?",
        "What measures will show whether progress is being made?",
        "What should people start, stop, or change in their day-to-day work?",
      ]),
      p("The further strategy moves away from the leadership team, the more practical it needs to become."),
      p("Employees cannot execute a strategic phrase. They need decisions, responsibilities, targets, and priorities that connect directly to their work."),
      p("This translation process is one of the most important parts of strategy execution, yet it is often treated as an afterthought."),
      h2("2. People Do Not Share the Same Understanding"),
      p("Leadership teams usually spend weeks developing a strategy."),
      p("They review market information, debate alternatives, challenge assumptions, and eventually agree on a direction."),
      p("By the end of the process, the strategy feels obvious to them because they understand all the thinking that sits behind it."),
      p("Most employees do not have that context."),
      p("They may encounter the strategy for the first time during a presentation, town hall, or email."),
      p("This creates an immediate information gap."),
      p("For strategy to work, people need more than a list of priorities. They need to understand:"),
      list([
        "Why the organization has chosen this direction.",
        "What has changed from the previous strategy.",
        "What the organization is choosing to prioritize.",
        "What is deliberately receiving less attention.",
        "How their own work contributes to the larger goal.",
      ]),
      p("Communication also needs repetition."),
      p("One presentation at the beginning of the year will not create sustained alignment. Strategic priorities need to appear consistently in leadership conversations, team meetings, performance discussions, resource decisions, and project reviews."),
      p("People understand what matters to an organization partly by observing what its leaders repeatedly pay attention to."),
      h2("3. Resources and Priorities Do Not Match"),
      p("A useful test of any strategy is to look at where the organization spends its money, time, and leadership attention."),
      p("If an initiative is described as strategically important but cannot secure funding, people, or executive attention, employees will quickly understand where it sits in the real hierarchy of priorities."),
      p("Strategy has consequences."),
      p("If digital transformation matters, technology capacity has to support it."),
      p("If growth in a new market is important, commercial resources need to move toward it."),
      p("If customer retention becomes a major priority, performance measures should reflect that."),
      p("This also means making trade-offs."),
      p("An organization cannot keep adding strategic initiatives without eventually stretching the same people and resources across too many competing demands."),
      p("Leadership therefore needs to answer a difficult question whenever a new priority is introduced:"),
      p("What will receive less attention as a result?"),
      p("Without that conversation, strategy can become a growing list of ambitions rather than a focused set of choices."),
      h2("Building a Better Execution Rhythm"),
      p("Once strategic priorities are translated and resources are aligned, organizations still need a system for keeping execution on track."),
      p("A strong execution rhythm typically includes:"),
      list([
        "Clear ownership: Every strategic priority has an accountable leader.",
        "Defined outcomes: Progress is measured against business outcomes, not simply activity.",
        "Regular reviews: Leadership reviews strategic initiatives frequently enough to intervene before problems become permanent.",
        "Fast escalation: Teams know how to raise issues that require executive decisions.",
        "Active reprioritization: Resources can move when circumstances or assumptions change.",
        "A willingness to stop: Initiatives that no longer make strategic or economic sense are closed rather than kept alive because someone has already invested time in them.",
      ]),
      p("The purpose of these reviews should be decision-making."),
      p("A strategy meeting filled entirely with status presentations creates information. A good strategy meeting creates decisions."),
      h2("Strategy Has to Become Part of Management"),
      p("I increasingly think of strategy execution as a management discipline rather than a separate phase that comes after strategy development."),
      p("The work is continuous."),
      p("Organizations make choices, allocate resources, execute, learn from what happens, and adjust."),
      p("Sometimes the original strategy proves correct and execution simply needs strengthening."),
      p("Sometimes market conditions change."),
      p("Sometimes the organization discovers that an assumption behind a strategic initiative was wrong."),
      p("A strong strategy process has room for all three possibilities."),
      p("The strategy document matters because it provides direction."),
      p("What ultimately determines performance, however, is whether hundreds of decisions across the organization begin to reflect that direction."),
      p("That requires clarity, shared understanding, aligned resources, and consistent follow-through."),
      p("Without those things, even an excellent strategy can remain little more than an excellent presentation."),
    ],
  },
  {
    slug: "three-lessons-leading-strategy-in-a-complex-industry",
    title: "3 Lessons I Learned Leading Strategy in a Complex Industry",
    category: "Strategy",
    description:
      "The neat version of strategy rarely survives contact with a real organization. Three lessons that have shaped how I think about strategy work.",
    date: "2026-08-05",
    readingTime: "2 min read",
    featured: true,
    body: [
      p("Working in strategy has taught me that the neat version of strategy we learn from frameworks rarely survives contact with a real organization."),
      p("The slides may look structured."),
      p("The business usually is not."),
      p("There are competing priorities, resource constraints, legacy decisions, stakeholder interests, regulatory realities, market uncertainty, and the simple challenge of getting different teams to move in the same direction."),
      p("Over time, three lessons have shaped how I think about strategy work."),
      h2("1. A good strategy needs organizational reality"),
      p("It is easy to design an ambitious strategy."),
      p("The harder question is whether the organization can execute it."),
      p("A company may want to launch several new products, enter new markets, transform operations, and reduce costs at the same time."),
      p("Each initiative may make sense independently."),
      p("Together, they may exceed the organization's capacity."),
      p("Strategy therefore has to account for people, systems, funding, leadership bandwidth, capabilities, and existing commitments."),
      p("Sometimes the smartest strategic decision is sequencing."),
      p("Do this first."),
      p("Build this capability next."),
      p("Enter that market later."),
      p("Ambition matters, but execution capacity matters too."),
      h2("2. Stakeholder management is part of strategy"),
      p("I used to think stakeholder management sat around the strategy."),
      p("Experience has taught me that it sits inside it."),
      p("Strategic decisions affect different groups differently."),
      p("A restructuring may improve efficiency while changing someone's span of control."),
      p("A new technology may improve productivity while creating uncertainty for employees."),
      p("A pricing decision may strengthen margins while creating pressure for commercial teams."),
      p("Ignoring these dynamics does not make them disappear."),
      p("Strong strategy leaders understand who will be affected, where resistance may come from, what concerns are legitimate, and where alignment needs to happen early."),
      p("A technically sound strategy can still fail when the people responsible for executing it do not support it."),
      h2("3. Execution discipline matters more than excitement"),
      p("Strategy launches often have energy."),
      p("People are enthusiastic. Leadership is aligned. Presentations look impressive."),
      p("Six months later, reality looks different."),
      p("Urgent operational issues have taken over. Some initiatives are behind schedule. Others have lost executive attention."),
      p("This is why strategy requires governance."),
      list([
        "Clear owners.",
        "Measurable outcomes.",
        "Regular reviews.",
        "Visible accountability.",
        "Fast escalation of blockers.",
      ]),
      p("And sometimes the discipline to stop initiatives that no longer make sense."),
      p("I have come to see strategy less as an annual event and more as a continuous management process."),
      p("You make choices, execute them, learn, adjust, and make new choices."),
      p("The frameworks help."),
      p("The harder work is building an organization capable of turning those frameworks into results."),
    ],
  },
  {
    slug: "three-signs-your-organization-is-ready-for-true-transformation",
    title: "3 Signs Your Organization Is Ready for True Transformation",
    category: "Transformation",
    description:
      "Transformation goes deeper than a new system or structure. Three signs that an organization is actually ready for that level of change.",
    date: "2026-07-29",
    readingTime: "2 min read",
    body: [
      p("Transformation is one of those words that gets used for almost everything."),
      p("A new technology platform becomes a digital transformation."),
      p("A restructuring becomes an organizational transformation."),
      p("A process improvement program becomes an operational transformation."),
      p("Some of these initiatives create meaningful change."),
      p("Others end up producing new systems and new structures while the organization continues working almost exactly as it did before."),
      p("True transformation goes deeper."),
      p("It changes how an organization operates, competes, serves customers, allocates resources, and makes decisions."),
      p("And there are usually signs that an organization is ready for that level of change."),
      h2("1. Leadership agrees that the current model cannot continue"),
      p("Transformation becomes difficult when leadership sees change as optional."),
      p("There needs to be a shared understanding of the problem."),
      p("Maybe customer expectations have changed. Costs are becoming unsustainable. Growth has slowed. Technology is disrupting the industry. Competitors are moving faster. Internal complexity is making execution difficult."),
      p("Whatever the trigger, leadership has to recognize that incremental improvements will not be enough."),
      p("This alignment matters because transformation eventually involves uncomfortable decisions."),
      p("Budgets may shift. Roles may change. Existing processes may disappear. Some initiatives may lose funding."),
      p("If leaders do not agree on the need for change, these decisions quickly become political."),
      h2("2. The organization is willing to change how work gets done"),
      p("Transformation cannot live only in strategy presentations."),
      p("Eventually, it reaches operating processes."),
      p("Teams may need different capabilities. Decision rights may have to change. Technology may replace manual work. Performance measures may need to be redesigned."),
      p("This is often where resistance begins."),
      p("Organizations ready for transformation understand that change may affect familiar routines and established power structures."),
      p("People need clarity about why the change matters, what will be different, and how they will be supported."),
      h2("3. Leadership is prepared to sustain attention"),
      p("Transformation takes time."),
      p("The launch usually gets the most energy."),
      p("There are town halls, workshops, project teams, communications, dashboards, and steering committees."),
      p("Then normal business pressure returns."),
      p("The organizations that succeed maintain leadership attention long after the initial excitement has disappeared."),
      p("They track outcomes, resolve bottlenecks, remove competing priorities, and hold people accountable."),
      p("They also adjust when assumptions change."),
      p("Transformation readiness ultimately comes down to willingness."),
      p("Willingness to acknowledge that the current model needs to evolve. Willingness to change how the organization works. And willingness to keep pushing after the project has lost its novelty."),
      p("Organizations that have those three things already have a strong foundation for meaningful transformation."),
    ],
  },
  {
    slug: "why-strategy-isnt-about-planning-its-about-prioritizing",
    title: "Why Strategy Isn't About Planning. It's About Prioritizing",
    category: "Strategy",
    description:
      "Planning tells you what could be done. Strategy becomes useful when leadership decides where limited resources should go first.",
    date: "2026-07-22",
    readingTime: "2 min read",
    body: [
      p("One of the most common outputs of a strategy process is a long list of initiatives."),
      p("Improve customer experience."),
      p("Expand into new markets."),
      p("Digitize operations."),
      p("Launch new products."),
      p("Reduce costs."),
      p("Strengthen talent."),
      p("Build brand awareness."),
      p("Increase revenue."),
      p("All of these may be sensible."),
      p("The problem is that an organization cannot pursue everything with the same level of intensity."),
      p("Strategy becomes useful when leadership decides where limited resources should go first."),
      p("That is prioritization."),
      h2("Planning tells you what could be done"),
      p("Planning is important."),
      p("Organizations need goals, initiatives, timelines, budgets, owners, and milestones."),
      p("But planning alone can create the illusion of strategic clarity."),
      p("A detailed roadmap may still contain too many competing ambitions."),
      p("The real challenge is deciding what deserves disproportionate attention."),
      p("If five initiatives compete for the same technology team, which one wins?"),
      p("If the business has enough capital to enter only one new market, which market matters most?"),
      p("If management attention is limited, which problems should leadership personally spend time solving?"),
      p("Those decisions reveal the strategy."),
      h2("Every priority consumes something"),
      p("Priorities require resources."),
      list(["Money.", "People.", "Time.", "Leadership attention.", "Organizational energy."]),
      p("This is why prioritization cannot happen only in a PowerPoint presentation."),
      p("The choices have to appear in the operating model."),
      p("A strategic initiative with no budget will struggle."),
      p("A priority without an accountable executive will drift."),
      p("A transformation program competing with ten other major projects will move slowly."),
      p("Organizations often need to reduce the number of things they are trying to do before execution improves."),
      h2("Saying no protects the strategy"),
      p("One of the hardest parts of strategy is turning down good opportunities."),
      p("Some opportunities will make money."),
      p("Some projects will solve genuine problems."),
      p("Some requests will come from influential stakeholders."),
      p("The question is whether they support the choices the organization has made."),
      p("Every additional initiative creates another demand on finite capacity."),
      p("That is why leadership teams need a consistent way to evaluate opportunities."),
      list([
        "Does this support our strategic priorities?",
        "What outcome will it create?",
        "What resources will it require?",
        "What will we delay or stop if we approve it?",
      ]),
      p("That final question forces clarity."),
      p("Most organizations do not suffer from a shortage of ideas."),
      p("They struggle with too many competing ones."),
      p("Prioritization gives strategy its power."),
    ],
  },
  {
    slug: "three-strategy-pitfalls-that-can-derail-even-a-good-strategy",
    title: "3 Strategy Pitfalls That Can Derail Even a Good Strategy",
    category: "Strategy",
    description:
      "A strategy can make perfect sense on paper and still struggle. Three pitfalls organizations should pay closer attention to, and the fix for each.",
    date: "2026-07-15",
    readingTime: "4 min read",
    body: [
      p("Most organizations do not struggle because they have no strategy."),
      p("There is usually a strategy document somewhere. Priorities have been agreed. Targets have been set. Leadership has probably spent hours debating where the business should go next."),
      p("The harder part is getting the organization to move in that direction consistently."),
      p("Over the years, working across strategy, transformation, and execution roles, I have seen a few patterns show up repeatedly. A strategy can make perfect sense on paper and still struggle once it meets the realities of competing priorities, limited resources, unclear ownership, and day-to-day operations."),
      p("Here are three pitfalls I think organizations should pay closer attention to."),
      h2("1. Trying to Do Too Much at Once"),
      p("One of the easiest ways to weaken a strategy is to call everything a priority."),
      p("You see a strategic plan with eight priorities, 20 initiatives and dozens of projects sitting underneath them. Each one may be reasonable on its own, but collectively they create a problem."),
      p("The organization simply does not have enough management attention, people, money or time to execute all of them well."),
      p("Teams end up spreading themselves across too many initiatives. Leaders spend meetings moving from one project update to another. Progress happens everywhere, but often not enough in the areas that matter most."),
      p("A good strategy requires choices."),
      h3("The fix: Force prioritization"),
      p("Leadership should be able to answer a few questions clearly:"),
      list([
        "What are the three to five outcomes that matter most over this period?",
        "Which initiatives will have the greatest impact on those outcomes?",
        "What are we deliberately choosing not to do?",
        "Where should our best people, capital and leadership attention go?",
      ]),
      p("That final question matters."),
      p("If something is genuinely a strategic priority, the way the organization allocates its resources should reflect that priority."),
      p("Strategy becomes much easier to execute when people know what deserves disproportionate attention."),
      h2("2. Leaving Strategy at the Leadership Level"),
      p("Another common problem is assuming that once leadership understands the strategy, the organization understands it too."),
      p("Usually, that is not the case."),
      p("A CEO may say, \"We need to improve customer retention.\""),
      p("The Head of Sales hears one thing. Operations hears another. Product interprets it differently. Someone three levels down may not know what the priority means for their work at all."),
      p("The strategy becomes weaker each time it travels through the organization."),
      p("Eventually, people return to doing what they have always done because nobody has translated the strategic priority into specific actions, targets and decisions."),
      h3("The fix: Translate strategy into execution"),
      p("Every strategic priority should cascade into clear outcomes at the relevant levels of the organization."),
      p("If improving customer retention is a priority, what does that mean for:"),
      list(["Product?", "Customer service?", "Sales?", "Operations?", "Technology?"]),
      p("Each team should understand the contribution it is expected to make, how that contribution will be measured and how it connects to the broader objective."),
      p("This is also where communication matters."),
      p("Mentioning the strategy once at an annual town hall is rarely enough. Leaders have to repeat it, explain it in different contexts and use it when making everyday decisions."),
      p("People understand what matters to an organization by watching what its leaders consistently talk about, measure and reward."),
      h2("3. Treating Strategy as an Annual Exercise"),
      p("I have seen organizations put significant effort into developing annual strategy plans."),
      p("There are workshops. Presentations. Financial models. Targets. Detailed initiatives."),
      p("Then everyone goes back to work."),
      p("Three months later, some initiatives have stalled. Others are behind schedule. A few no longer make sense because market conditions have changed. Yet the strategy is barely discussed until the next planning cycle."),
      p("That creates a gap between strategy development and strategy management."),
      p("A strategy should not become static simply because the planning process is complete."),
      h3("The fix: Build a strategy execution rhythm"),
      p("Execution needs a cadence."),
      p("For each strategic priority, there should be clear ownership, measurable outcomes and regular reviews."),
      p("A monthly or quarterly strategy review should answer questions such as:"),
      list([
        "Are we making the progress we expected?",
        "Which initiatives are behind?",
        "What is preventing execution?",
        "Have any assumptions changed?",
        "Do we need to reallocate resources?",
        "Does an initiative need to be stopped entirely?",
      ]),
      p("These conversations should focus on decisions rather than lengthy status updates."),
      p("Sometimes the right response to poor performance is to push harder. Sometimes the underlying assumption behind an initiative has changed and the strategy itself needs to evolve."),
      p("Strong execution requires knowing the difference."),
      h2("Strategy Is a Management Discipline"),
      p("Writing a strategy is only one part of the work."),
      p("The real test comes afterwards."),
      p("Can the organization make difficult choices about what matters most? Can it translate those choices into clear responsibilities across teams? Can leadership maintain enough discipline to review progress, resolve bottlenecks and adjust when circumstances change?"),
      p("Organizations that do these things consistently give their strategies a much better chance of succeeding."),
      p("Because ultimately, a strategy creates value through the hundreds of decisions, resource allocations and actions that happen after the strategy deck has been closed."),
    ],
  },
  {
    slug: "the-three-horizons-of-innovation",
    title: "The 3 Horizons of Innovation: Balancing Now, Next & New",
    category: "Transformation",
    description:
      "Where should leaders invest for growth? The Three Horizons framework offers a useful way to balance today's business against tomorrow's.",
    date: "2026-07-08",
    readingTime: "2 min read",
    body: [
      p("One of the hardest questions leaders face is where to invest for growth."),
      p("The business needs to perform today."),
      p("It also needs to prepare for tomorrow."),
      p("And somewhere inside the organization, people need to be thinking about opportunities that may not generate meaningful revenue for several years."),
      p("Those priorities compete for the same resources."),
      p("The Three Horizons framework provides a useful way to think about the balance."),
      h2("Horizon 1: Protect and improve the core"),
      p("Horizon 1 is today's business."),
      p("These are the products, services, customers, and markets currently generating most of the organization's revenue."),
      p("Innovation here usually focuses on improvement."),
      p("How can we serve customers better?"),
      p("How can we lower costs?"),
      p("How can we improve the product?"),
      p("How can we increase conversion, retention, or productivity?"),
      p("This work may sound less exciting than launching something completely new, but it matters."),
      p("The core business usually funds everything else."),
      p("Ignoring it in the pursuit of future growth can weaken the entire organization."),
      h2("Horizon 2: Build emerging growth engines"),
      p("Horizon 2 includes opportunities that are showing potential but have not yet become major contributors."),
      p("That could mean entering a new customer segment, launching an adjacent product, expanding geographically, or developing a new distribution channel."),
      p("These opportunities need investment and patience."),
      p("They also need different expectations."),
      p("A new business cannot always be evaluated using the same metrics as a mature business."),
      p("Early-stage growth may require leaders to pay more attention to adoption, learning, customer feedback, and product-market fit."),
      h2("Horizon 3: Explore the future"),
      p("Horizon 3 contains longer-term bets."),
      list(["New technologies.", "New business models.", "Unfamiliar markets.", "Ideas whose commercial potential may still be uncertain."]),
      p("Most Horizon 3 ideas will never become large businesses."),
      p("That is normal."),
      p("The purpose is to create options for the future."),
      p("The challenge is balance."),
      p("Organizations under pressure often concentrate entirely on Horizon 1 because today's numbers feel urgent."),
      p("Other organizations become fascinated by future innovation while neglecting the business that funds it."),
      p("Strong innovation portfolios create room for all three."),
      p("Improve what works today."),
      p("Build the opportunities that could drive tomorrow."),
      p("Keep exploring what may matter after that."),
      p("Innovation becomes more sustainable when leaders stop treating every opportunity as if it belongs to the same timeline."),
    ],
  },
  {
    slug: "innovation-dies-when-fear-leads",
    title: "Innovation Dies When Fear Leads: How Culture Kills Great Ideas",
    category: "Leadership",
    description:
      "Sometimes employees aren't the problem. The environment is. How fear quietly teaches people to stop sharing ideas, and what changes it.",
    date: "2026-07-01",
    readingTime: "2 min read",
    body: [
      p("I have always found it interesting when organizations say employees are not innovative enough."),
      p("Sometimes the employees are not the problem."),
      p("The environment is."),
      p("People learn quickly what is safe inside an organization."),
      p("They notice what happens when someone challenges a senior colleague. They see how managers respond when an experiment fails. They watch whether unusual ideas are explored or dismissed."),
      p("Over time, employees build an internal map of acceptable behavior."),
      p("If speaking up creates risk, people become quieter."),
      p("If failure attracts blame, people become cautious."),
      p("If every new idea requires several layers of approval, people stop trying."),
      p("And gradually, an organization that says it wants innovation creates a culture designed to prevent it."),
      h2("Fear makes people optimize for safety"),
      p("Innovation involves proposing something that may not work."),
      p("That requires psychological and professional safety."),
      p("Employees need to believe they can ask questions, challenge assumptions, and suggest alternatives without damaging their reputation."),
      p("This does not mean every idea should be approved."),
      p("Some ideas will be impractical. Others will be poorly thought through."),
      p("The important thing is how the organization responds."),
      p("A respectful \"no\" keeps people thinking."),
      p("Ridicule, punishment, or automatic dismissal teaches people to stay silent."),
      h2("Leaders shape the innovation culture"),
      p("Employees rarely take cultural cues from posters on the wall."),
      p("They watch leaders."),
      p("When someone brings a different perspective into a meeting, does the manager become defensive or curious?"),
      p("When a pilot underperforms, does leadership ask what was learned or look for someone to blame?"),
      p("When junior employees identify problems, are they taken seriously?"),
      p("These moments matter more than innovation workshops."),
      h2("Make small bets easier"),
      p("One reason innovation becomes intimidating is that organizations treat every new idea like a major investment decision."),
      p("Many ideas do not need that level of commitment."),
      p("A team can test a new process for two weeks."),
      p("A product concept can be piloted with a small customer segment."),
      p("A new service approach can be tested in one location."),
      p("Small experiments reduce the cost of failure while increasing the speed of learning."),
      p("Culture determines whether those experiments happen."),
      p("When employees know they can challenge assumptions, test ideas responsibly, and learn from what does not work, innovation becomes part of everyday behavior."),
      p("Fear has the opposite effect."),
      p("People rarely stop having ideas."),
      p("They simply stop sharing them."),
    ],
  },
  {
    slug: "why-some-strategies-fail-the-people-problem",
    title: "Why Some Strategies Fail: The People Problem",
    category: "Strategy",
    description:
      "A strategy can be logically sound and still fail. Usually because people, not the plan, were never accounted for.",
    date: "2026-06-24",
    readingTime: "2 min read",
    body: [
      p("A strategy can be logically sound and still fail."),
      p("The market analysis may be correct."),
      p("The financial case may be convincing."),
      p("The initiatives may make sense."),
      p("The targets may even be achievable."),
      p("And yet, months later, progress is slow."),
      p("One reason is that organizations sometimes design strategy as though people will automatically behave differently once a new direction has been announced."),
      p("They usually will not."),
      p("People carry existing incentives, habits, priorities, relationships, fears, and ways of working into the new strategy."),
      p("If those things remain unchanged, execution becomes difficult."),
      h2("People need to understand what the strategy means for them"),
      p("Senior leaders may understand the strategic narrative perfectly."),
      p("Employees often receive a simplified version during a town hall or through an email."),
      p("That leaves an important gap."),
      list([
        "What should I do differently?",
        "Which priorities have changed?",
        "What should I stop doing?",
        "How will success be measured?",
      ]),
      p("When those questions are unanswered, people default to familiar behavior."),
      p("Strategy becomes another leadership initiative running alongside normal work."),
      h2("Incentives can quietly defeat strategy"),
      p("Imagine an organization says collaboration is critical, but individual performance metrics reward teams for protecting their own targets."),
      p("Or leadership says customer experience is the priority, but employees are measured primarily on speed."),
      p("People eventually respond to what gets measured and rewarded."),
      p("This is why strategy execution requires alignment between strategic priorities and the performance system."),
      p("The organization has to make the desired behavior rational."),
      h2("Managers translate strategy into reality"),
      p("Middle managers play an underrated role."),
      list([
        "They decide what teams discuss every week.",
        "They allocate work.",
        "They resolve trade-offs.",
        "They interpret leadership messages.",
        "They shape how seriously employees take new priorities.",
      ]),
      p("If managers are not aligned, equipped, and accountable, strategic messages can lose meaning as they travel through the organization."),
      p("This is why communication alone rarely solves execution problems."),
      p("People need context, clarity, capability, incentives, and reinforcement."),
      p("A strategy becomes real when thousands of individual decisions begin moving in the same direction."),
      p("The strategy document matters."),
      p("The people who have to bring it to life matter even more."),
    ],
  },
  {
    slug: "eight-career-lessons-i-keep-coming-back-to",
    title: "Eight Career Lessons I Keep Coming Back To",
    category: "Career",
    description:
      "Eight lessons on growth, reputation, relationships, and leadership, gathered one birthday at a time.",
    date: "2026-06-17",
    readingTime: "3 min read",
    body: [
      p("Birthdays tend to make me reflective."),
      p("One of mine recently had me thinking about how much my understanding of work has changed since I started my career."),
      p("Some lessons came from opportunities that went well. Others came from mistakes, difficult feedback, disappointments, and moments when I was given more responsibility than I felt ready for."),
      p("I expect some of these lessons will continue to evolve, but these eight have shaped how I approach my career today."),
      h2("1. Growth Requires Difficult Work"),
      p("The periods when I have grown fastest have rarely been the most comfortable ones."),
      p("Stretch roles expose gaps."),
      p("They force you to think differently, develop new capabilities, and solve problems without having every answer."),
      p("That discomfort is often evidence that you are operating beyond what you already know."),
      h2("2. Relationships Compound Over Time"),
      p("Your skills matter, but careers also move through people."),
      p("Someone mentions your name for an opportunity."),
      p("A former colleague recommends you for a role."),
      p("A leader who has worked with you before asks you to join another project."),
      p("Those moments are usually built on trust accumulated over time."),
      p("Strong professional relationships should not begin only when you need something."),
      h2("3. Reputation Is Built in Ordinary Moments"),
      p("It is easy to perform well when the presentation is important and senior leadership is watching."),
      p("Reputation is also shaped by smaller moments."),
      p("How do you respond under pressure?"),
      p("Do you meet deadlines?"),
      p("How do you treat junior colleagues?"),
      p("What happens when you make a mistake?"),
      p("Can people trust your word?"),
      p("Consistency eventually becomes reputation."),
      h2("4. Clarity Often Comes From Movement"),
      p("Some career decisions cannot be solved entirely through analysis."),
      p("You can research, seek advice, and think carefully, but eventually you have to move."),
      p("I have made meaningful career decisions without feeling completely certain about the outcome."),
      p("The next step often revealed information I could not have discovered while standing still."),
      h2("5. Feedback Becomes More Valuable When You Stop Fighting It"),
      p("Earlier in my career, critical feedback could feel embarrassing."),
      p("My first instinct was sometimes to explain."),
      p("Over time, I have become more interested in what the feedback can teach me."),
      p("A useful approach is to ask:"),
      list([
        "What specifically should I do differently?",
        "Where have you seen this show up?",
        "What would better performance look like?",
        "What should I continue doing?",
      ]),
      p("Specific feedback is much easier to act on."),
      h2("6. Put Your Hand Up for the Difficult Projects"),
      p("You will rarely feel completely prepared for the opportunities that stretch you most."),
      p("Sometimes you have to volunteer before you know exactly how you will deliver."),
      p("The key is understanding the difference between a stretch and something you genuinely cannot handle."),
      p("If you can learn quickly, ask for help, and put in the work, difficult projects can accelerate your development significantly."),
      h2("7. Learn From Mistakes Quickly"),
      p("You will get things wrong."),
      p("A bad decision does not need to become a permanent label."),
      p("Review what happened."),
      p("Understand your role in it."),
      p("Change your approach."),
      p("Then move forward."),
      p("The ability to learn quickly from mistakes is more useful than trying to build a career in which you never make one."),
      h2("8. People Remember How Leadership Feels"),
      p("Deadlines matter."),
      p("Targets matter."),
      p("Quality matters."),
      p("The people doing the work matter too."),
      p("I have seen how differently teams respond when they feel respected, trusted, and supported by their leaders."),
      p("Good leadership does not remove accountability."),
      p("It creates an environment where people understand the standard and believe the person holding them accountable also wants them to succeed."),
      h2("Career Growth Is Broader Than Promotion"),
      p("I used to think about career growth largely through roles, titles, and progression."),
      p("I now think about it more broadly."),
      p("Am I better at solving difficult problems?"),
      p("Has my judgment improved?"),
      p("Can I handle greater responsibility?"),
      p("Am I better at working with people?"),
      p("Do people trust me?"),
      p("Am I becoming the kind of leader I would want to work with?"),
      p("Titles still matter."),
      p("But those questions tell me much more about whether I am genuinely growing."),
    ],
  },
  {
    slug: "the-real-cost-of-ignoring-innovation",
    title: "The Real Cost of Ignoring Innovation: Lessons from Kodak and Nokia",
    category: "Transformation",
    description:
      "Kodak and Nokia weren't unaware of what was happening. Their challenge was deeper, and it's a lesson every market leader should sit with.",
    date: "2026-06-10",
    readingTime: "2 min read",
    body: [
      p("Kodak and Nokia are often used as cautionary stories in conversations about innovation."),
      p("Both companies were dominant in their industries."),
      p("Kodak became almost synonymous with photography. Nokia once controlled a huge share of the global mobile phone market."),
      p("And both eventually lost their positions as their industries changed around them."),
      p("The interesting part is that neither company was completely unaware of what was happening."),
      p("Kodak famously developed one of the earliest digital cameras in the 1970s. Nokia had strong engineering capabilities, global distribution, a powerful brand, and significant resources."),
      p("Their challenge was deeper."),
      p("Successful business models can make change uncomfortable."),
      p("When an organization has spent years building capabilities, revenue streams, processes, and incentives around a particular model, new ideas can feel threatening."),
      p("A new technology may create opportunity for the company while simultaneously weakening the business that currently pays the bills."),
      p("That creates a difficult strategic tension."),
      h2("Success can make organizations defensive"),
      p("When a business model is working, protecting it feels rational."),
      p("Leaders are responsible for revenue, profitability, market share, and shareholder expectations. Investments in unfamiliar technologies may look risky compared with continuing to invest in proven products."),
      p("The problem comes when protecting today's business prevents the organization from building tomorrow's."),
      p("Kodak's film business was highly profitable. Digital photography challenged the economics of that business."),
      p("Nokia's dominance in mobile hardware became less valuable as smartphones increasingly competed through software ecosystems, applications, and user experience."),
      p("The market changed faster than their organizations could respond."),
      h2("Innovation requires cannibalization sometimes"),
      p("One of the hardest strategic decisions is choosing to disrupt your own successful product."),
      p("Leaders naturally hesitate."),
      p("Why launch something that could reduce revenue from your existing offer?"),
      p("Because if customer behavior is changing, someone else may do it anyway."),
      p("Organizations that innovate well are willing to place selective bets on businesses that may eventually compete with their current model."),
      h2("Pay attention to weak signals"),
      p("Major disruption rarely arrives completely unannounced."),
      p("Customer preferences shift gradually. New competitors appear at the edges of the market. Technologies improve. Business models that once looked niche begin to scale."),
      p("The organizations that respond early have more options."),
      p("The cost of ignoring innovation goes far beyond losing market share."),
      p("You lose time."),
      p("And once an industry has moved significantly, catching up becomes much more expensive."),
      p("The lesson from Kodak and Nokia is simple."),
      p("Market leadership is temporary."),
      p("Organizations have to keep earning their relevance."),
    ],
  },
  {
    slug: "strategy-is-not-a-plan-its-a-set-of-choices",
    title: "Strategy Is Not a Plan. It's a Set of Choices",
    category: "Strategy",
    description:
      "The most useful strategy question isn't what will we do. It's what has the organization decided not to do.",
    date: "2026-06-03",
    readingTime: "2 min read",
    body: [
      p("Many strategy documents are impressive."),
      p("They contain market analysis, financial projections, strategic pillars, initiatives, timelines, and pages of detailed recommendations."),
      p("But there is one question I often find more useful than almost anything else:"),
      p("What has the organization decided not to do?"),
      p("That question reveals how much real strategy has taken place."),
      p("A plan can contain dozens of activities."),
      p("Strategy requires choices."),
      p("Every organization has limited capital, people, management attention, and time. Choosing one direction means accepting that some other opportunities will receive less attention."),
      p("That is where strategy becomes difficult."),
      h2("Choices create focus"),
      p("Imagine a company deciding it wants to grow."),
      p("That sounds strategic, but it leaves many questions unanswered."),
      list([
        "Grow where?",
        "New customers or existing customers?",
        "New markets or existing markets?",
        "Premium products or mass market?",
        "Organic growth or acquisitions?",
        "Which customer segments matter most?",
        "What capabilities will the organization need?",
      ]),
      p("Until those choices are made, \"growth\" remains an ambition."),
      p("Good strategy gives the organization enough clarity to allocate resources confidently."),
      h2("Priorities need consequences"),
      p("Organizations frequently describe five, eight, or even ten things as strategic priorities."),
      p("The problem is that something cannot be a priority if it has no effect on how the organization behaves."),
      p("If customer experience is a priority, there should be investment behind it."),
      p("If digital transformation is a priority, technology capacity should reflect that."),
      p("If a new market is strategically important, leadership attention should move toward it."),
      p("Strategy shows up in budgets, hiring decisions, project portfolios, leadership agendas, and performance metrics."),
      p("That is where you see the choices."),
      h2("Trade-offs are uncomfortable"),
      p("One reason organizations avoid clear choices is that trade-offs create tension."),
      p("Every initiative has an advocate."),
      p("Every business unit believes its priorities are important."),
      p("Every opportunity can usually be supported by a reasonable argument."),
      p("Leadership has to decide which opportunities deserve disproportionate investment."),
      p("That may mean delaying a project, exiting a market, reducing investment in an existing product, or saying no to something that could still be profitable."),
      p("Those decisions are rarely easy."),
      p("But avoiding them does not eliminate the trade-off. It simply spreads resources more thinly."),
      p("A strong strategy gives people clarity about where the organization is going and what matters most along the way."),
      p("The quality of the strategy is often visible in the choices leadership is willing to make."),
    ],
  },
  {
    slug: "innovation-should-be-part-of-everyones-job",
    title: "Innovation Should Be Part of Everyone's Job",
    category: "Leadership",
    description:
      "Some of the best opportunities for improvement sit with the people closest to customers and processes. An innovation team alone cannot see all of them.",
    date: "2026-05-27",
    readingTime: "3 min read",
    body: [
      p("When organizations talk about innovation, there is often an assumption that someone needs to own it."),
      p("So an innovation team is created. A Chief Innovation Officer is appointed. An innovation lab is launched. A few people are given responsibility for finding new ideas while everyone else gets on with running the business."),
      p("There is nothing inherently wrong with having a dedicated innovation function. In some organizations, it can provide the structure, expertise, and investment needed to explore new opportunities."),
      p("The problem begins when innovation becomes something only that team is expected to do."),
      p("Some of the best opportunities for improvement are sitting with people who encounter customers, processes, products, and operational problems every day. An innovation function cannot see all of them."),
      p("That is why I think innovation works best when it becomes an organizational discipline rather than simply a departmental responsibility."),
      h2("Innovation Is Often Much Smaller Than We Imagine"),
      p("The word \"innovation\" tends to make us think about major breakthroughs."),
      p("But innovation can also be much more practical."),
      p("It can mean:"),
      list([
        "Redesigning a frustrating customer journey.",
        "Automating a repetitive internal process.",
        "Finding a cheaper way to deliver an existing service.",
        "Using data differently to make better decisions.",
        "Changing a product based on recurring customer feedback.",
        "Removing unnecessary approval layers that slow teams down.",
        "Testing a new way of reaching customers.",
      ]),
      p("None of these necessarily requires an innovation lab."),
      p("They require people who are willing to look at how things currently work and ask whether they could work better."),
      p("That mindset can exist anywhere in an organization."),
      h2("Give People Permission to Challenge Existing Ways of Working"),
      p("Most organizations have processes that exist because someone designed them years ago."),
      p("Over time, circumstances change. Technology improves. Customer expectations evolve. Teams grow."),
      p("The process remains."),
      p("The people closest to the work often know which parts no longer make sense, but knowing something is inefficient does not automatically mean people will challenge it."),
      p("Culture matters."),
      p("If questioning an established process is interpreted as being difficult, people learn to work around problems instead of fixing them."),
      p("Managers can change this by asking better questions:"),
      list([
        "What creates unnecessary work for your team?",
        "What do customers complain about repeatedly?",
        "Which process would you redesign if you could?",
        "What are we doing manually that technology could simplify?",
        "What is one thing we could test differently this month?",
      ]),
      p("Questions like these make improvement part of normal management conversations."),
      h2("Make Experimentation Easier"),
      p("Another barrier to innovation is the size of the process surrounding it."),
      p("A small idea sometimes needs a detailed business case, several meetings, multiple approvals, and a significant budget before anyone can test whether it works."),
      p("By then, enthusiasm has disappeared."),
      p("Organizations can create a simpler path for low-risk experiments."),
      p("A good pilot should have:"),
      list([
        "A clear problem or hypothesis.",
        "A defined scope.",
        "A small budget where necessary.",
        "A reasonable timeframe.",
        "Clear measures of success.",
        "Someone responsible for capturing what was learned.",
      ]),
      p("If it works, expand it."),
      p("If it does not, understand why and move on."),
      h2("Leaders Determine Whether Innovation Survives"),
      p("People watch how leaders respond to ideas."),
      p("If every new suggestion is immediately met with reasons it cannot work, employees eventually stop suggesting things."),
      p("If unsuccessful experiments lead to blame, teams become conservative."),
      p("If leaders show curiosity, ask questions, and create space for thoughtful experimentation, people behave differently."),
      p("This is why an innovation culture cannot be delegated entirely to an innovation team."),
      p("The function can provide frameworks, funding, expertise, and coordination."),
      p("The wider organization still needs to create the ideas, challenge assumptions, test improvements, and learn."),
      p("Innovation becomes powerful when people stop waiting for permission to think about how things could work better."),
      p("At that point, innovation has stopped being a department."),
      p("It has become part of how the organization works."),
    ],
  },
  {
    slug: "the-career-mistake-i-made-by-keeping-my-head-down",
    title: "The Career Mistake I Made by Keeping My Head Down",
    category: "Career",
    description:
      "People cannot recognize work they do not see or fully understand. What I've learned about visibility, relationships, and asking for what you want.",
    date: "2026-05-20",
    readingTime: "3 min read",
    body: [
      p("Early in my career, I believed that doing good work was enough."),
      p("My approach was simple: keep my head down, deliver what was expected of me, avoid unnecessary politics, and trust that good performance would eventually be recognized."),
      p("It sounded sensible."),
      p("There was only one problem."),
      p("People cannot recognize work they do not see or fully understand."),
      p("That was one of my earliest lessons about how careers work inside organizations."),
      p("I still believe strongly in competence and good work. Nothing replaces them. But I have also learned that career growth depends on how well people understand your contribution, the relationships you build, and whether the right people know what you are capable of doing."),
      h2("Good Work Does Not Always Travel"),
      p("When you are close to your own work, it is easy to assume everyone knows what you are doing."),
      p("They usually do not."),
      p("Your manager has their own responsibilities."),
      p("Senior leaders may only encounter a fraction of the projects happening across the organization."),
      p("Colleagues in other functions may have no idea what your team has delivered."),
      p("This becomes particularly important when decisions are being made about:"),
      list([
        "Promotions.",
        "Stretch assignments.",
        "High-profile projects.",
        "Leadership opportunities.",
        "Succession planning.",
        "New roles.",
      ]),
      p("If nobody in the room understands the value you have created, your work cannot advocate for itself."),
      h2("Visibility Does Not Have to Mean Bragging"),
      p("For a long time, I was uncomfortable with the idea of \"being visible\" because I associated it with self-promotion."),
      p("I have since learned that there is a professional way to communicate your contribution."),
      p("You can:"),
      list([
        "Give concise updates on important work.",
        "Explain the business impact of what you delivered.",
        "Share useful lessons from a project.",
        "Present your team's work when opportunities arise.",
        "Document results ahead of performance conversations.",
      ]),
      p("There is a difference between constantly talking about yourself and making sure stakeholders understand the work you are responsible for."),
      h2("Build Relationships Before You Need Them"),
      p("Another lesson was the importance of relationships."),
      p("The strongest professional relationships I have built were rarely created because I needed something immediately."),
      p("They developed through working together, being dependable, helping someone solve a problem, sharing information, and staying connected."),
      p("Over time, those relationships create trust."),
      p("And trust matters because careers often move through conversations you are not present for."),
      p("Someone recommends you for a project."),
      p("A former colleague tells someone you would be good for a role."),
      p("A leader remembers how you handled a difficult assignment."),
      p("Relationships allow your reputation to travel further than your immediate work."),
      h2("Ask for What You Want"),
      p("Managers are not mind readers."),
      p("You may want a promotion, exposure to a different function, a more challenging project, or an opportunity to lead."),
      p("Your manager may have no idea."),
      p("Career conversations should therefore be specific."),
      p("Ask:"),
      list([
        "What capabilities do I need to demonstrate at the next level?",
        "Where do you think I have the biggest development gap?",
        "What projects would give me the right exposure?",
        "What would make you comfortable giving me more responsibility?",
      ]),
      p("The answers can give you a much clearer development plan than simply waiting to be noticed."),
      h2("Excellence Still Comes First"),
      p("None of this replaces good work."),
      p("Visibility without substance eventually becomes obvious."),
      p("Relationships cannot permanently compensate for poor performance."),
      p("The foundation still has to be competence, reliability, and the ability to create value."),
      p("What changed for me was understanding that good work needs context."),
      p("People need to know what you contributed."),
      p("They need to experience how you work."),
      p("And sometimes, they need you to tell them where you want to go next."),
      p("Your work should speak for you."),
      p("I simply no longer expect it to do all the talking."),
    ],
  },
  {
    slug: "three-small-habits-that-improved-my-productivity",
    title: "Three Small Habits That Improved My Productivity",
    category: "Productivity",
    description:
      "The habits that helped most weren't sophisticated. They worked because they reduced the thinking required to get started and stay focused.",
    date: "2026-05-13",
    readingTime: "3 min read",
    body: [
      p("I used to think becoming more productive required a sophisticated system."),
      p("Maybe I needed a detailed morning routine, a better productivity app, a perfectly organized calendar, or one of those elaborate planning systems that seems to work beautifully for everyone online."),
      p("I tried different approaches."),
      p("Eventually, I realized that the habits that helped me most were much simpler."),
      p("They worked because they reduced the amount of thinking required to get started and helped me stay focused when the day became busy."),
      p("Three habits have been particularly useful."),
      h2("1. Start the Day With Three Priorities"),
      p("A long to-do list can create the illusion of organization."),
      p("Mine sometimes contained everything from an important work deliverable to replying to a message."),
      p("The problem was that every task appeared to have equal importance."),
      p("So I started reducing the day to three priorities."),
      p("I ask myself:"),
      p("If I complete only three meaningful things today, what should they be?"),
      p("Those become the anchor for the day."),
      p("There will still be emails, calls, meetings, requests, and smaller tasks. But I know which three things should not disappear underneath everything else."),
      p("This has helped me distinguish between being busy and making progress."),
      p("A useful daily priority should ideally:"),
      list([
        "Move an important project forward.",
        "Resolve something that has been blocking progress.",
        "Complete a meaningful deliverable.",
        "Address something important that I have been postponing.",
      ]),
      p("Three is enough to create focus without making the day unrealistic."),
      h2("2. Make the First Step Smaller"),
      p("I have found that procrastination is often less about the work itself and more about starting."),
      p("A task feels large, so you tell yourself you need two uninterrupted hours."),
      p("You do not have two hours, so you postpone it."),
      p("Then the task feels even larger tomorrow."),
      p("One habit that helped me was reducing the commitment."),
      p("Instead of \"finish the presentation,\" the first step might be:"),
      list([
        "Open the existing deck.",
        "Review the storyline.",
        "Draft the first two slides.",
        "Work for fifteen minutes.",
      ]),
      p("Once I have started, I often continue."),
      p("And even when I do not, the task is easier to return to because I am no longer starting from zero."),
      p("This has been particularly useful for work that requires concentration."),
      p("Waiting for perfect conditions can become another form of procrastination."),
      h2("3. Close the Day Properly"),
      p("For a long time, my workday ended when I became too tired to continue."),
      p("The laptop might close, but mentally I was still working."),
      p("I would remember unfinished tasks later in the evening or start thinking about what I needed to do the next morning."),
      p("A short end-of-day review helped."),
      p("Before finishing, I ask:"),
      list([
        "What did I complete today?",
        "What remains open?",
        "What needs my attention tomorrow?",
        "Is there anything I need to capture before I forget it?",
      ]),
      p("Then I write down the next day's starting point."),
      p("This creates a sense of closure and makes the following morning easier."),
      h2("Simplicity Makes Consistency Easier"),
      p("None of these habits is groundbreaking."),
      p("That is probably part of why they have worked for me."),
      p("Productivity systems often fail when maintaining the system becomes another task."),
      p("I prefer habits that are simple enough to survive a busy week."),
      p("Choose what matters."),
      p("Make it easier to start."),
      p("Close the day with clarity."),
      p("Small habits may not feel transformative while you are doing them."),
      p("Repeated consistently, they can change how you work."),
    ],
  },
  {
    slug: "five-lessons-from-would-you-hire-you",
    title: "Five Lessons From Would You Hire You? That Made Me Reflect on How I Work",
    category: "Career",
    description:
      "Five ideas from Matt Adolphe's Would You Hire You? that changed how I think about solving problems, building trust, and my own blind spots.",
    date: "2026-05-06",
    readingTime: "3 min read",
    body: [
      p("I recently read Would You Hire You? by Matt Adolphe, and the title alone asks a useful question."),
      p("Most of us naturally evaluate our careers from our own perspective."),
      p("We know how hard we are trying."),
      p("We know the pressures we are dealing with."),
      p("We understand our intentions."),
      p("The people we work with experience something different."),
      p("They experience our output, attitude, reliability, judgment, communication, and how we behave when things become difficult."),
      p("That makes \"Would you hire you?\" a more challenging question than it initially appears."),
      p("Five ideas from the book stayed with me."),
      h2("1. Bring Solutions, Not Only Problems"),
      p("Spotting problems is useful."),
      p("It becomes much more valuable when you can also think about what could happen next."),
      p("That does not mean you need to have the perfect solution before raising an issue."),
      p("A better approach is:"),
      list([
        "Explain the problem clearly.",
        "Show why it matters.",
        "Identify what may be causing it.",
        "Suggest one or two possible responses.",
        "Ask for input where necessary.",
      ]),
      p("This changes you from someone who reports problems into someone who helps solve them."),
      h2("2. Become Someone People Want on Their Team"),
      p("Competence matters enormously."),
      p("But most of us have worked with someone who was technically excellent and still made every project exhausting."),
      p("How you work with people matters too."),
      p("Are you dependable?"),
      p("Do you communicate?"),
      p("Can you disagree respectfully?"),
      p("Do you take ownership when something goes wrong?"),
      p("Can people trust you to do what you said you would do?"),
      p("These qualities may not always appear in a job description, but they influence how people experience working with you."),
      h2("3. Pay Attention to Your Blind Spots"),
      p("Feedback can be uncomfortable because it occasionally conflicts with the version of ourselves we have in our heads."),
      p("I have learned to become more curious about it."),
      p("Not every piece of feedback will be accurate or useful."),
      p("Patterns deserve attention."),
      p("If different people are independently telling you the same thing, there may be something worth examining."),
      p("The goal is to ask:"),
      list([
        "What specifically are they observing?",
        "When does this behavior show up?",
        "What impact is it having?",
        "What could I do differently?",
      ]),
      p("Feedback becomes more useful when translated into behavior."),
      h2("4. Consistency Builds Trust"),
      p("Your best day does not define your reputation."),
      p("Your normal days do."),
      p("People notice whether you meet commitments consistently, maintain quality under pressure, and follow through when nobody is chasing you."),
      p("That reliability creates trust."),
      p("And trust often leads to larger responsibilities."),
      h2("5. Your Professional Reputation Is Always Developing"),
      p("We sometimes reduce personal brand to what appears publicly."),
      p("A significant part of your reputation is built privately."),
      p("It is built in meetings."),
      p("In emails."),
      p("During difficult projects."),
      p("In how you treat people who cannot do anything for your career."),
      p("In what you do when you make a mistake."),
      p("In whether people can depend on you."),
      p("That is why I found the book's central question useful."),
      p("Would you hire you?"),
      p("Would you want yourself on an important project?"),
      p("Would you trust yourself with greater responsibility?"),
      p("Would you enjoy managing yourself?"),
      p("If any of those answers make you uncomfortable, that is not necessarily a bad thing."),
      p("It may simply show you where the next stage of your growth needs to begin."),
    ],
  },
  {
    slug: "what-getting-passed-over-for-a-promotion-taught-me",
    title: "What Getting Passed Over for a Promotion Taught Me",
    category: "Career",
    description:
      "Being passed over forced me to look at progression differently. What I learned about readiness, feedback, and what the next level actually requires.",
    date: "2026-04-22",
    readingTime: "3 min read",
    body: [
      p("There was a point in my career when promotion announcements came out and several of my peers moved to the next level."),
      p("My name was not on the list."),
      p("I had expected it to be."),
      p("Other people expected it too."),
      p("So I asked for feedback."),
      p("The answer was straightforward: my performance review had not demonstrated the expectations required for the next level."),
      p("That was difficult to hear because I genuinely thought I had done enough."),
      p("With hindsight, that experience became one of the more useful moments in my career because it forced me to look at progression differently."),
      p("Working hard and being ready for the next level are not always the same thing."),
      h2("1. Get Curious Before You Get Defensive"),
      p("Disappointment naturally creates explanations."),
      p("Maybe the decision was political."),
      p("Maybe someone overlooked your contribution."),
      p("Maybe the process was unfair."),
      p("Any of those things could be true."),
      p("But I think the first step should still be understanding the feedback."),
      p("I needed to know:"),
      list([
        "Where specifically had I fallen short?",
        "What did the next level require?",
        "What evidence was missing?",
        "What could I realistically improve?",
      ]),
      p("Those questions gave me something useful to work with."),
      h2("2. Understand What the Next Level Requires"),
      p("One of the biggest lessons was that performing well in your current role does not automatically prove readiness for the next one."),
      p("Promotion often requires different evidence."),
      p("Depending on the role, that could mean:"),
      list([
        "Taking greater ownership.",
        "Managing more complex stakeholders.",
        "Leading other people.",
        "Making decisions with less supervision.",
        "Handling ambiguity.",
        "Thinking beyond your immediate tasks.",
        "Demonstrating stronger commercial or strategic judgment.",
      ]),
      p("These expectations are not always obvious."),
      p("Ask."),
      p("Speak to your manager."),
      p("Talk to people already operating at that level."),
      p("Understand what good performance looks like before the next promotion cycle begins."),
      h2("3. Turn Feedback Into a Development Plan"),
      p("Feedback is much easier to use when it becomes specific."),
      p("Instead of \"I need to be more strategic,\" ask what strategic behavior would look like in your role."),
      p("Maybe it means bringing recommendations instead of only analysis."),
      p("Maybe it means understanding the commercial implications of your work."),
      p("Maybe it means thinking across functions instead of only within your immediate responsibility."),
      p("The more specific the gap, the easier it becomes to close."),
      h2("4. Look for Opportunities to Demonstrate the Change"),
      p("Not long after my promotion disappointment, I had the opportunity to work on a major client project."),
      p("It was complex and demanding."),
      p("It also gave me the chance to demonstrate some of the capabilities I needed to strengthen."),
      p("That experience taught me something important."),
      p("Development cannot happen only in theory."),
      p("You need situations that allow people to experience you operating differently."),
      p("Look for projects that stretch the exact capability you are trying to build."),
      h2("5. Decide What the Feedback Means for You"),
      p("Being passed over does not automatically mean you should stay and try harder."),
      p("Sometimes the feedback is useful and the opportunity to grow exists."),
      p("Sometimes expectations are unclear."),
      p("Sometimes the organization cannot offer the progression you want."),
      p("Sometimes it may genuinely be time to leave."),
      p("The important thing is making that decision after you understand what happened."),
      h2("Focus on Becoming Ready"),
      p("Promotion decisions will never sit entirely within your control."),
      p("Budgets change."),
      p("Structures change."),
      p("Opportunities disappear."),
      p("Other candidates may simply be stronger."),
      p("What you can control is whether you are becoming more capable."),
      p("That experience changed how I approach career progression."),
      p("I ask for feedback earlier."),
      p("I pay more attention to what the next level requires."),
      p("And I look for opportunities to demonstrate those capabilities before the formal promotion conversation begins."),
      p("Getting passed over was disappointing."),
      p("It was also useful information."),
      p("What I did with that information mattered much more."),
    ],
  },
  {
    slug: "how-to-grow-when-you-feel-invisible-at-work",
    title: "How to Grow When You Feel Invisible at Work",
    category: "Career",
    description:
      "Doing good work isn't always enough to get seen. Practical ways to build visibility, and how to know when the real problem is the environment.",
    date: "2026-04-15",
    readingTime: "3 min read",
    body: [
      p("There are periods in a career when you can feel as though you are doing everything right without making much progress."),
      p("You deliver."),
      p("You meet deadlines."),
      p("You work hard."),
      p("Yet someone else gets the interesting project. Someone else is invited to the important meeting. Someone else receives the recognition."),
      p("I have learned that there are several reasons this can happen."),
      p("Sometimes there is a performance gap you have not recognized."),
      p("Sometimes your organization offers limited opportunities."),
      p("And sometimes you are doing good work that too few people know enough about."),
      p("If the last situation sounds familiar, there are practical ways to change it."),
      h2("1. Speak When You Have Something Useful to Add"),
      p("Visibility does not require becoming the loudest person in every meeting."),
      p("Useful contribution is enough."),
      p("Ask a thoughtful question."),
      p("Share an observation."),
      p("Volunteer an update."),
      p("Offer a solution."),
      p("If you have done the analysis, present the conclusion rather than automatically allowing someone else to speak for the work."),
      p("Over time, people begin associating you with the quality of your thinking."),
      h2("2. Document Your Impact"),
      p("Do not wait until performance-review season to remember what you did six months ago."),
      p("Keep a simple record of:"),
      list([
        "Projects delivered.",
        "Problems solved.",
        "Revenue or savings generated.",
        "Processes improved.",
        "Responsibilities you took on.",
        "Positive stakeholder feedback.",
        "Difficult situations you handled.",
        "Results supported by numbers.",
      ]),
      p("This is useful for performance discussions, CV updates, promotion conversations, and your own reflection."),
      p("More importantly, it helps you describe your contribution accurately."),
      h2("3. Ask for Specific Feedback"),
      p("If you feel stuck, find out whether other people see something you do not."),
      p("Avoid asking only, \"How am I doing?\""),
      p("Ask questions that produce usable information:"),
      list([
        "What is one thing I should do differently?",
        "What would you need to see before giving me more responsibility?",
        "Which capability should I develop next?",
        "Where do you think I am underperforming relative to my potential?",
      ]),
      p("Then pay attention to patterns in the answers."),
      h2("4. Work Beyond Your Immediate Team"),
      p("Cross-functional work is one of the best ways to expand both your perspective and your professional relationships."),
      p("It exposes you to different problems and different leaders."),
      p("It also allows people outside your immediate team to experience your work."),
      p("Look for:"),
      list([
        "Strategic projects.",
        "Transformation initiatives.",
        "Working groups.",
        "Cross-functional problem-solving teams.",
        "Opportunities to present your team's work.",
        "Projects involving senior stakeholders.",
      ]),
      p("Choose opportunities where you can make a genuine contribution, not simply attend more meetings."),
      h2("5. Put Yourself Forward"),
      p("Some opportunities will come to you."),
      p("Others require you to ask."),
      p("Tell your manager that you want a stretch assignment."),
      p("Volunteer to lead a workstream."),
      p("Ask whether you can present the analysis you developed."),
      p("Express interest in the project everyone assumes is above your level."),
      p("You will not get every opportunity."),
      p("But waiting silently significantly reduces the number available to you."),
      h2("Know When the Problem Is the Environment"),
      p("There is also an important limit to all this advice."),
      p("You can improve your visibility, strengthen your skills, seek feedback, and consistently deliver good work, yet still find yourself in an environment with limited room for growth."),
      p("At that point, the question changes."),
      p("Instead of asking, \"How do I get them to see me?\" you may need to ask whether this is still the right place for the next stage of your career."),
      p("Visibility should help good work travel."),
      p("It cannot create opportunities where none exist."),
      p("The goal is to become good at understanding the difference."),
    ],
  },
  {
    slug: "learn-from-giants-before-you-become-one",
    title: "Learn From Giants Before You Become One",
    category: "Career",
    description:
      "David Ogilvy's nesting-doll lesson was about hiring, but there's a career lesson inside it too. You don't have to be a manager to surround yourself with giants.",
    date: "2026-04-08",
    readingTime: "3 min read",
    body: [
      p("There is a well-known story about David Ogilvy and Russian nesting dolls."),
      p("When he appointed a new office head, he would reportedly give the person a set of nesting dolls. Inside the smallest was a message explaining that if leaders consistently hired people smaller than themselves, the organization would eventually become a company of dwarfs. If they hired people bigger than themselves, they would build a company of giants."),
      p("It is a leadership lesson about hiring talented people without being threatened by them."),
      p("I think there is also a useful career lesson inside it."),
      p("You do not have to be a manager before you can surround yourself with giants."),
      p("Early in your career, you can make deliberate choices about the people you learn from, the projects you join, and the standards you expose yourself to."),
      p("Those choices can accelerate your growth."),
      h2("Find People Who Are Better Than You at Something"),
      p("Being the strongest person in the room can feel good."),
      p("Being around people who expose the gaps in your ability can be much more useful."),
      p("Look for people who:"),
      list([
        "Think more clearly than you.",
        "Communicate complex ideas simply.",
        "Have stronger commercial judgment.",
        "Manage stakeholders well.",
        "Lead teams you would want to work in.",
        "Consistently produce excellent work.",
        "Handle pressure with maturity.",
      ]),
      p("You do not need to copy them."),
      p("Observe what they do differently."),
      h2("Choose Projects That Increase Your Exposure"),
      p("Some projects teach you more because of the people involved."),
      p("If you have an opportunity to work alongside someone whose work you respect, take it seriously."),
      p("Watch how they prepare."),
      p("Notice the questions they ask."),
      p("Pay attention to how they structure problems."),
      p("See how they respond when a senior stakeholder disagrees."),
      p("Observe what happens before the polished final output appears."),
      p("That behind-the-scenes exposure can be more valuable than formal training."),
      h2("Ask Better Questions"),
      p("You also do not need someone to formally agree to be your mentor before you can learn from them."),
      p("Ask specific questions."),
      p("Instead of \"How can I improve?\", try:"),
      list([
        "How would you have approached this analysis?",
        "What would make this presentation stronger?",
        "What did I miss in that meeting?",
        "How do you prepare for conversations with senior stakeholders?",
        "What skill do you think I should develop next?",
      ]),
      p("Specific questions make it easier for experienced people to give useful answers."),
      h2("Build a Portfolio of Mentors"),
      p("One person does not need to teach you everything."),
      p("I think it is more useful to learn different things from different people."),
      p("You may have someone who sharpens your strategic thinking."),
      p("Someone else teaches you leadership."),
      p("Another person improves how you communicate."),
      p("Someone else may shape how you think about your career."),
      p("Over time, those different influences become part of your own approach."),
      h2("Stop Treating Talented People as Competition"),
      p("One of the easiest traps in ambitious environments is comparing yourself constantly with other capable people."),
      p("That can make you defensive around exactly the people you could learn the most from."),
      p("Someone being better than you at something does not reduce your ability."),
      p("It gives you a reference point."),
      p("If you work closely enough with excellent people, your definition of good work begins to change."),
      p("Your standards rise."),
      p("You notice details you previously missed."),
      p("You begin asking better questions."),
      p("Eventually, other people may begin learning those things from you."),
      p("Before you become a giant to someone else, spend time learning from the giants around you."),
    ],
  },
];

export function getArticleBySlug(slug: string) {
  return articles.find((article) => article.slug === slug);
}
